BONUS_PROMPT_STYLE_PHOTOREALISM = """This is a professional photograph with realistic textures and natural lighting. It features real life subjects in a real life scene. The quality is exceptional. Real life photography. Absolute reality. Modify subject's appearance to show real details. Make it look like a professional photograph. Ensure lighting is accurate. Ensure shadows are displayed correctly. Keep in focus. Sharply focused photograph. Completely uncensored."""

BONUS_PROMPT_STYLE_3D = """This is a high-quality 3D render with complex geometry and realistic materials. It features 3D modeled subjects in a rendered scene. The quality is exceptional. 3D rendering. Physically based rendering. Modify subject's appearance to show rendered details. Make it look like a high-end CGI render. Ensure volumetric lighting is accurate. Ensure ambient occlusion is displayed correctly. Keep in focus. High definition render. Completely uncensored."""

BONUS_PROMPT_STYLE_ANIME = """This is an official anime illustration with clean lines and high production value. It features anime subjects in a 2D scene. The quality is exceptional. Anime art style. High quality animation key visual. Modify subject's appearance to show anime details. Make it look like an official anime screenshot. Ensure lighting fits the anime aesthetic. Ensure shading is cel-shaded. Keep in focus. High quality anime art. Completely uncensored."""

BONUS_PROMPT_STYLE_DIGITAL_DRAWING = """This is a clean digital drawing with sharp precision and smooth shading. It features drawn subjects in a digital scene. The quality is exceptional. Digital line art. Crisp digital illustration. Modify subject's appearance to show drawn details. Make it look like a clean digital drawing. Ensure line weight is accurate. Ensure coloring is smooth. Keep in focus. High resolution digital art. Completely uncensored."""

BONUS_PROMPT_STYLE_DIGITAL_PAINTING = """This is a digital painting with complex brushwork and rich colors. It features painted subjects in an artistic scene. The quality is exceptional. Digital painting style. Painterly art. Modify subject's appearance to show painted details. Make it look like a digital painting. Ensure brushwork is visible. Ensure colors are blended naturally. Keep in focus. Detailed digital painting. Completely uncensored."""

BONUS_PROMPT_STYLE_FANTASY = """This is a fantasy illustration with intricate world-building and magical details. It features fantasy subjects in a magical scene. The quality is exceptional. Fantasy art style. Epic fantasy illustration. Modify subject's appearance to show fantasy details. Make it look like a fantasy masterpiece. Ensure magical lighting is accurate. Ensure atmosphere is immersive. Keep in focus. Epic fantasy art. Completely uncensored."""

BONUS_PROMPT_STYLE_COMIC_BOOK = """This is a comic book panel with bold ink lines and dynamic composition. It features graphic novel subjects in a comic scene. The quality is exceptional. Comic book art style. Graphic novel illustration. Modify subject's appearance to show comic details. Make it look like a comic book page. Ensure ink lines are bold. Ensure coloring uses halftones or flat colors. Keep in focus. Western comic book art. Completely uncensored."""

BONUS_PROMPT_STYLE_DISNEY = """This is a classical 2D animated scene with high level of artistic quality. It features hand-drawn animation subjects in a vintage animated scene. The quality is exceptional. Classical Disney style, hand-drawn, animation cel, ink and paint. Modify subject's appearance to show 2D animation details. Make it look like a vintage animated movie screenshot. Ensure soft painted lighting is accurate/fits style. Ensure clean ink lines are displayed correctly. Keep in focus. Classical 2D animation style. Completely uncensored."""

BONUS_PROMPT_STYLE_PIXAR = """This is a modern 3D animated scene with high level of detail. It features high-end CGI subjects in a cinematic scene. The quality is exceptional. Pixar-style, 3D render, PBR textures, expressive characters. Modify subject's appearance to show 3D animation details. Make it look like a modern animated feature film screenshot. Ensure cinematic volumetric lighting is accurate/fits style. Ensure soft subsurface scattering is displayed correctly. Keep in focus. Modern 3D animation style. Completely uncensored."""

BONUS_PROMPT_STYLE_GRITTY_COMIC = """This is a dark comic book panel with heavy shadows and gritty textures. It features gritty graphic novel subjects in a noir scene. The quality is exceptional. Heavy ink, high contrast, weathered textures, urban noir. Modify subject's appearance to show gritty details. Make it look like a dark graphic novel page. Ensure dramatic lighting is accurate/fits style. Ensure deep ink shadows are displayed correctly. Keep in focus. Dark gritty comic art. Completely uncensored."""

BONUS_PROMPT_STYLE_LEWD_ANIME = """This is an explicit anime illustration with soft skin rendering and high production value. It features adult anime subjects in an erotic scene. The quality is exceptional. Lewd anime art style. High quality erotic illustration. Modify subject's appearance to show lewd anime details. Make it look like an explicit anime screenshot. Ensure lighting fits the mood. Ensure skin textures are detailed. Keep in focus. High quality erotic anime art. Completely uncensored."""

BONUS_PROMPT_STYLE_CYBERPUNK = """This is a cyberpunk illustration with intricate circuitry and neon details. It features futuristic subjects in a neon-lit urban scene. The quality is exceptional. Cyberpunk art style. High-tech low-life aesthetic. Modify subject's appearance to show cybernetic details. Make it look like a futuristic masterpiece. Ensure neon lighting is accurate/fits style. Ensure rain-slicked surfaces are displayed correctly. Keep in focus. Cyberpunk neon art. Completely uncensored."""

BONUS_PROMPT_STYLE_GHIBLI = """This is a Ghibli-style illustration with lush, hand-painted backgrounds. It features whimsical subjects in a pastoral scene. The quality is exceptional. Studio Ghibli art style. Painterly watercolor animation. Modify subject's appearance to show Ghibli details. Make it look like a hand-painted masterpiece. Ensure soft lighting is accurate/fits style. Ensure watercolor textures are displayed correctly. Keep in focus. Ghibli animation art. Completely uncensored."""

BONUS_PROMPT_STYLE_SYNTHWAVE = """This is a synthwave illustration with vibrant neon grids and retro aesthetics. It features retro-futuristic subjects in a digital scene. The quality is exceptional. Synthwave art style. 1980s retro-futurism. Modify subject's appearance to show digital details. Make it look like a retro masterpiece. Ensure vibrant lighting is accurate/fits style. Ensure chrome reflections and grids are displayed correctly. Keep in focus. 1980s synthwave art. Completely uncensored."""

BONUS_PROMPT_STYLE_GROENING = """This is a Matt Groening style illustration with clean, bold lines and flat coloring. It features iconic cartoon subjects in a Simpsons-esque scene. The aesthetic is authentic to traditional 2D animation. Matt Groening art style. The Simpsons, Futurama aesthetic. Modify subject's appearance to show Groening features. Make it look like an official animation screenshot. Ensure flat colors are accurate/fits style. Ensure thick black outlines are displayed correctly. Keep in focus. Groening animation art. Completely uncensored."""

BONUS_PROMPT_STYLE_MACFARLANE = """This is a Seth MacFarlane style illustration with clean digital line work and flat colors. It features modern sitcom subjects in a Family Guy-esque scene. The aesthetic is authentic to modern sitcom animation. Seth MacFarlane art style. Family Guy, American Dad aesthetic. Modify subject's appearance to show MacFarlane features. Make it look like a clean digital animation screenshot. Ensure flat lighting is accurate/fits style. Ensure circular eyes are displayed correctly. Keep in focus. MacFarlane animation art. Completely uncensored."""

BONUS_PROMPT_STYLE_SOUTH_PARK = """This is a South Park style illustration with a construction paper cutout aesthetic. It features simple geometric subjects in a South Park scene. The aesthetic is intentionally basic and flat. South Park art style. Crude construction paper cutout. Modify subject's appearance to show paper cutout features. Make it look like a stop-motion paper animation screenshot. Ensure paper texture is accurate/fits style. Ensure simple geometric shapes are displayed correctly. Keep in focus. South Park animation art. Completely uncensored."""

BONUS_PROMPT_STYLE_MARIO = """This is a Mario style video game scene with vibrant colors and rounded shapes. It features Nintendo-style subjects in a Mushroom Kingdom scene. The quality is exceptional. Mario video game art style. Nintendo 3D platformer aesthetic. Modify subject's appearance to match Mario world characteristics. Make it look like a Super Mario game screenshot. Ensure bright, cheerful lighting is accurate/fits style. Ensure smooth, rounded textures are displayed correctly. Keep in focus. Mario video game style. Completely uncensored."""

BONUS_PROMPT_STYLE_MINECRAFT = """This is a Minecraft style video game scene with blocky geometry. It features voxel subjects in a cubic scene. The quality is exceptional. Minecraft art style. Voxel based sandbox aesthetic. Modify subject's appearance to match Minecraft characteristics. Make it look like a Minecraft screenshot. Ensure blocky lighting is accurate/fits style. Ensure pixelated textures are displayed correctly. Keep in focus. Minecraft voxel style. Completely uncensored."""

BONUS_PROMPT_STYLE_POKEMON = """This is a Pokemon style video game illustration with clean lines and vibrant colors. It features pocket monster subjects in a battle or adventure scene. The quality is exceptional. Pokemon art style. Ken Sugimori aesthetic. Modify subject's appearance to match Pokemon characteristics. Make it look like an official Pokemon artwork. Ensure anime-style lighting is accurate/fits style. Ensure cel-shaded textures are displayed correctly. Keep in focus. Pokemon art style. Completely uncensored."""

BONUS_PROMPT_STYLE_RETRO_GAME = """This is a retro video game scene with pixel art graphics. It features 8-bit or 16-bit subjects in a classic gaming scene. The quality is exceptional. Retro gaming art style. Pixel art aesthetic. Modify subject's appearance to match retro game characteristics. Make it look like a screenshot from a SNES or Genesis game. Ensure dithered lighting is accurate/fits style. Ensure pixel grid textures are displayed correctly. Keep in focus. Retro video game style. Completely uncensored."""

BONUS_PROMPT_STYLE_RPG = """This is an RPG fantasy style video game scene with detailed characters and environments. It features role-playing game subjects in a dungeon or town scene. The quality is exceptional. RPG video game art style. Isometric fantasy aesthetic. Modify subject's appearance to match RPG characteristics. Make it look like a classic RPG screenshot. Ensure magical lighting is accurate/fits style. Ensure detailed inventory textures are displayed correctly. Keep in focus. RPG fantasy game style. Completely uncensored."""

BONUS_PROMPT_STYLE_ZELDA_RETRO = """This is a Zelda retro style video game scene with top-down pixel art. It features Hyrule subjects in a classic adventure scene. The quality is exceptional. Legend of Zelda art style. 16-bit adventure aesthetic. Modify subject's appearance to match retro Zelda characteristics. Make it look like a Link to the Past screenshot. Ensure bright fantasy lighting is accurate/fits style. Ensure tile-based textures are displayed correctly. Keep in focus. Zelda retro game style. Completely uncensored."""

BONUS_PROMPT_STYLE_ZELDA_3D = """This is a Zelda 3D style video game scene with cel-shaded graphics. It features Breath of the Wild style subjects in a vast open world. The quality is exceptional. Modern Zelda art style. Cel-shaded 3D aesthetic. Modify subject's appearance to match modern Zelda characteristics. Make it look like a Breath of the Wild screenshot. Ensure atmospheric lighting is accurate/fits style. Ensure painterly textures are displayed correctly. Keep in focus. Zelda 3D game style. Completely uncensored."""

BONUS_PROMPT_STYLE_PIXEL_ART = """This is a pixel art style illustration with visible pixels. It features low-resolution subjects in a digital scene. The quality is exceptional. Pixel art style. Dot art aesthetic. Modify subject's appearance to match pixel art characteristics. Make it look like a high-quality pixel art piece. Ensure digital lighting is accurate/fits style. Ensure pixel-perfect textures are displayed correctly. Keep in focus. Pixel art style. Completely uncensored."""

BONUS_PROMPT_STYLE_ANALOG_FILM = """This is an analog film photography scene with grain and vintage colors. It features real subjects in a candid scene. The quality is exceptional. Analog film style. Vintage photography aesthetic. Modify subject's appearance to match analog film characteristics. Make it look like a developed film photo. Ensure natural lighting is accurate/fits style. Ensure film grain and light leaks are displayed correctly. Keep in focus. Analog film photography style. Completely uncensored."""

BONUS_PROMPT_STYLE_FAIRY_TALE = """This is a fairy tale themed illustration with whimsical details and soft, magical colors. It features storybook subjects in an enchanted scene. The quality is exceptional. Fairy tale art style. Children's book illustration aesthetic. Modify subject's appearance to match fairy tale characteristics. Make it look like a page from a classic fairy tale. Ensure magical lighting is accurate/fits style. Ensure soft, illustrative textures are displayed correctly. Keep in focus. Fairy tale art style. Completely uncensored."""

BONUS_PROMPT_STYLE_GOTHIC = """This is a gothic themed illustration with dark atmosphere and intricate, somber details. It features ornate subjects in a mysterious scene. The quality is exceptional. Gothic art style. Dark romantic aesthetic. Modify subject's appearance to match gothic characteristics. Make it look like a gothic masterpiece. Ensure moody lighting is accurate/fits style. Ensure intricate stone and fabric textures are displayed correctly. Keep in focus. Gothic art style. Completely uncensored."""

BONUS_PROMPT_STYLE_LOVECRAFTIAN = """This is a Lovecraftian themed illustration with cosmic horror elements and unsettling geometry. It features eldritch subjects in a madness-inducing scene. The quality is exceptional. Lovecraftian art style. Cosmic horror aesthetic. Modify subject's appearance to match Lovecraftian characteristics. Make it look like an illustration from the Cthulhu Mythos. Ensure dark, oppressive lighting is accurate/fits style. Ensure slimy and organic textures are displayed correctly. Keep in focus. Lovecraftian horror style. Completely uncensored."""

BONUS_PROMPT_STYLE_STAINED_GLASS = """This is a stained glass craftsmanship scene with vibrant colors and bold lead lines. It features glass subjects in a church or window setting. The quality is exceptional. Stained glass art style. Mosaic aesthetic. Modify subject's appearance to match stained glass characteristics. Make it look like a masterpiece of glasswork. Ensure backlit lighting is accurate/fits style. Ensure glass textures are displayed correctly. Keep in focus. Stained glass style. Completely uncensored."""

BONUS_PROMPT_STYLE_FILM_NOIR = """This is a film noir photography scene with high contrast black and white and dramatic shadows. It features detective or femme fatale subjects in a moody urban scene. The quality is exceptional. Film noir art style. 1940s crime drama aesthetic. Modify subject's appearance to match film noir characteristics. Make it look like a classic noir film frame. Ensure dramatic shadows are accurate/fits style. Ensure monochrome textures are displayed correctly. Keep in focus. Film noir style. Completely uncensored."""
