BONUS_PROMPT_STYLE_PHOTOREALISM = """This is a professional photograph with realistic textures and natural lighting. It features real life subjects in a real life scene. The quality is exceptional. Real life photography. Absolute reality. Modify any subjects' appearance to show real details. Make it look like a professional photograph. Ensure lighting is accurate. Ensure shadows are displayed correctly. Keep in focus. The image is a sharply focused photograph."""

BONUS_PROMPT_STYLE_3D = """This is a high-quality 3D render with complex geometry and realistic materials. It features 3D modeled subjects in a rendered scene. The quality is exceptional. 3D rendering. Physically based rendering. Modify any subjects' appearance to show rendered details. Make it look like a high-end CGI render. Ensure volumetric lighting is accurate. Ensure ambient occlusion is displayed correctly. Keep in focus. The image is a high definition render."""

BONUS_PROMPT_STYLE_ANIME = """This is an official anime key visual with clean lines and high production value. It features anime subjects in a 2D scene. The quality is exceptional. Anime art style. High quality animation key visual. Modify any subjects' appearance to show anime details. Make it look like an official anime movie still. Ensure lighting fits the anime aesthetic. Ensure shading is cel-shaded. Keep in focus. The image is reminiscent of high quality anime art."""

BONUS_PROMPT_STYLE_DIGITAL_DRAWING = """This is a clean digital drawing with sharp precision and smooth shading. It features drawn subjects in a digital scene. The quality is exceptional. Digital line art. Crisp digital illustration. Modify any subjects' appearance to show drawn details. Make it look like a clean digital drawing. Ensure line weight is accurate. Ensure coloring is smooth. Keep in focus. The image is a high resolution digital art piece."""

BONUS_PROMPT_STYLE_DIGITAL_PAINTING = """This is a digital painting with complex brushwork and rich colors. It features painted subjects in an artistic scene. The quality is exceptional. Digital painting style. Painterly art. Modify any subjects' appearance to show painted details. Make it look like a digital painting. Ensure brushwork is visible. Ensure colors are blended naturally. Keep in focus. The image is a detailed digital painting."""

BONUS_PROMPT_STYLE_FANTASY = """This is a fantasy artwork with intricate world-building and magical details. It features fantasy subjects in a magical scene. The quality is exceptional. Fantasy art style. Epic fantasy illustration. Modify any subjects' appearance to show fantasy details. Make it look like a fantasy masterpiece. Ensure magical lighting is accurate. Ensure atmosphere is immersive. Keep in focus. The image is reminiscent of epic fantasy art."""

BONUS_PROMPT_STYLE_COMIC_BOOK = """This is a comic book panel with bold ink lines and dynamic composition. It features graphic novel subjects in a dynamic scene. The quality is exceptional. Comic book art style. Graphic novel illustration. Modify any subjects' appearance to show comic details. Make it look like a comic book page. Ensure ink lines are bold. Ensure coloring uses flat colors. Keep in focus. The image is reminiscent of western comic book art."""

BONUS_PROMPT_STYLE_DISNEY = """This is a scene in the classic 2D animation style of Disney animated films, featuring hand-drawn cels and fluid character movement. It features hand-drawn animation subjects in a vintage animated scene. The quality is exceptional. Disney animation style, hand-drawn, animation cel, ink and paint. Modify any subjects' appearance to match the classic golden age 2D animation style. Make it look like a still from a classic animated feature film. Ensure soft painted lighting is accurate to the style. Ensure clean ink lines are displayed correctly. Keep in focus. The image is reminiscent of classic golden age 2D animation."""

BONUS_PROMPT_STYLE_PIXAR = """This is a scene in the modern 3D animation style of Pixar animated films, featuring high-quality rendering and expressive designs. It features high-end CGI subjects in a cinematic scene. The quality is exceptional. Pixar animation style, 3D render, PBR textures, expressive characters. Modify any subjects' appearance to match the high-end 3D rendering style. Make it look like a still from a modern 3D animated feature film. Ensure cinematic volumetric lighting is accurate to the style. Ensure soft subsurface scattering is displayed correctly. Keep in focus. The image is reminiscent of high-end 3D computer animation."""

BONUS_PROMPT_STYLE_GRITTY_COMIC = """This is a dark comic book panel with heavy shadows and gritty textures. It features gritty graphic novel subjects in a noir scene. The quality is exceptional. Heavy ink, high contrast, weathered textures, urban noir. Modify any subjects' appearance to show gritty details. Make it look like a dark graphic novel page. Ensure dramatic lighting is accurate to the style. Ensure deep ink shadows are displayed correctly. Keep in focus. The image is reminiscent of dark gritty comic art."""

BONUS_PROMPT_STYLE_LEWD_ANIME = """This is an explicit anime key visual with soft skin rendering and high production value. It features adult anime subjects in an erotic scene. The quality is exceptional. Lewd anime art style. High quality erotic illustration. Modify any subjects' appearance to show lewd anime details. Make it look like an explicit anime movie still. Ensure lighting fits the mood. Ensure skin textures are detailed. Keep in focus. The image is reminiscent of high quality erotic anime art."""

BONUS_PROMPT_STYLE_CYBERPUNK = """This is a cyberpunk scene with intricate circuitry and neon details. It features futuristic subjects in a neon-lit urban scene. The quality is exceptional. Cyberpunk art style. High-tech low-life aesthetic. Modify any subjects' appearance to show cybernetic details. Make it look like a futuristic masterpiece. Ensure neon lighting is accurate to the style. Ensure rain-slicked surfaces are displayed correctly. Keep in focus. The image is reminiscent of cyberpunk neon art."""

BONUS_PROMPT_STYLE_GHIBLI = """This is an animation frame in the hand-painted watercolor style of Studio Ghibli animated films, featuring lush backgrounds and whimsical subjects. It features whimsical subjects in a pastoral scene. The quality is exceptional. Studio Ghibli animation style, hand-painted watercolor, lush backgrounds. Modify any subjects' appearance to match the painterly anime style. Make it look like a still from a hand-painted anime film. Ensure soft lighting is accurate to the style. Ensure watercolor textures are displayed correctly. Keep in focus. The image is reminiscent of a painterly anime aesthetic."""

BONUS_PROMPT_STYLE_SYNTHWAVE = """This is a synthwave scene with vibrant neon grids and retro aesthetics. It features retro-futuristic subjects in a digital scene. The quality is exceptional. Synthwave art style. 1980s retro-futurism. Modify any subjects' appearance to show digital details. Make it look like a retro masterpiece. Ensure vibrant lighting is accurate to the style. Ensure chrome reflections and grids are displayed correctly. Keep in focus. The image is reminiscent of 1980s synthwave art."""

BONUS_PROMPT_STYLE_GROENING = """This is an animation frame in the satirical cartoon style of the animated series The Simpsons, featuring clean, bold lines and flat coloring. It features iconic cartoon subjects in a satirical cartoon scene. The aesthetic is authentic to traditional 2D animation. Satirical 2D animation aesthetic. Modify any subjects' appearance to match the traditional 2D animation style with clean, bold outlines. Make it look like an official animation screenshot. Ensure flat colors are accurate to the style. Ensure thick black outlines are displayed correctly. Keep in focus. The image is reminiscent of traditional 2D animation with bold outlines."""

BONUS_PROMPT_STYLE_MACFARLANE = """This is an animation frame in the modern sitcom animation style of the animated series Family Guy, featuring clean digital line work and flat colors. It features modern sitcom subjects in a modern animated sitcom scene. The aesthetic is authentic to modern sitcom animation. Modern adult sitcom animation aesthetic. Modify any subjects' appearance to match the flat digital sitcom animation style. Make it look like a clean digital animation screenshot. Ensure flat lighting is accurate to the style. Ensure clean digital linework is displayed correctly. Keep in focus. The image is reminiscent of modern digital sitcom animation."""

BONUS_PROMPT_STYLE_SOUTH_PARK = """This is an animation frame in the construction paper cutout style of the animated series South Park, featuring simple subjects in a satirical scene. The aesthetic is intentionally basic and flat. Crude construction paper cutout animation style. Modify any subjects' appearance to match the crude construction paper cutout animation style. Make it look like a stop-motion paper animation screenshot. Ensure paper texture is accurate to the style. Ensure flat articulation is displayed correctly. Keep in focus. The image is reminiscent of crude construction paper animation."""

BONUS_PROMPT_STYLE_MARIO = """This is a scene in the 3D video game style of Super Mario video games, featuring vibrant colors and rounded geometry. It features cartoonish subjects in a vibrant, colorful world. The quality is exceptional. Vibrant 3D video game aesthetic. Modify any subjects' appearance to match the vibrant 3D platformer video game style. Make it look like a still from a 3D platformer game. Ensure bright, cheerful lighting is accurate to the style. Ensure smooth, rounded textures are displayed correctly. Keep in focus. The image is reminiscent of vibrant 3D platformer games."""

BONUS_PROMPT_STYLE_MINECRAFT = """This is a scene in the voxel-based video game style of the video game Minecraft, featuring blocky graphics. It features voxel subjects in a cubic scene. The quality is exceptional. Voxel-based video game aesthetic. Modify any subjects' appearance to match the blocky voxel-based game style. Make it look like a still from a voxel-based game. Ensure blocky lighting is accurate to the style. Ensure pixelated textures are displayed correctly. Keep in focus. The image is reminiscent of a blocky voxel-based art style."""

BONUS_PROMPT_STYLE_POKEMON = """This is artwork in the anime style of the Pokemon animated series, featuring clean lines and vibrant cel-shaded designs. It features collectible creature subjects in an adventure scene. The quality is exceptional. Official Pokemon art style. Modify any subjects' appearance to match the clean cel-shaded anime style. Make it look like official anime art. Ensure anime-style lighting is accurate to the style. Ensure cel-shaded textures are displayed correctly. Keep in focus. The image is reminiscent of clean cel-shaded anime."""

BONUS_PROMPT_STYLE_RETRO_GAME = """This is a retro video game scene with pixel art graphics. It features 8-bit and 16-bit subjects in a classic gaming scene. The quality is exceptional. Retro gaming art style. Pixel art aesthetic. Modify any subjects' appearance to match retro game aesthetics. Make it look like a screenshot from a retro gameing console game. Ensure dithered lighting is accurate to the style. Ensure pixel grid textures are displayed correctly. Keep in focus. The image is reminiscent of a retro video game style."""

BONUS_PROMPT_STYLE_RPG = """This is an RPG fantasy style video game scene with detailed characters and environments. It features role-playing game themed subjects and scene. The quality is exceptional. RPG video game art style. Isometric fantasy aesthetic. Modify any subjects' appearance to match RPG aesthetics. Make it look like a classic RPG screenshot. Ensure magical lighting is accurate to the style. Ensure detailed inventory textures are displayed correctly. Keep in focus. The image is reminiscent of an RPG fantasy game style."""

BONUS_PROMPT_STYLE_ZELDA_RETRO = """This is a scene in the 16-bit video game style of the video game The Legend of Zelda: A Link to the Past, featuring top-down pixel art. It features fantasy subjects in a classic adventure scene. The quality is exceptional. 16-bit adventure aesthetic. Modify any subjects' appearance to match the classic 16-bit adventure game style. Make it look like a still from a 16-bit video game. Ensure bright fantasy lighting is accurate to the style. Ensure tile-based textures are displayed correctly. Keep in focus. The image is reminiscent of classic 16-bit adventure games."""

BONUS_PROMPT_STYLE_ZELDA_3D = """This is a scene in the cel-shaded 3D video game style of the video game The Legend of Zelda: Breath of the Wild, featuring painterly textures. It features cel-shaded subjects in a vast open world. The quality is exceptional. Cel-shaded 3D adventure aesthetic. Modify any subjects' appearance to match the cel-shaded 3D adventure game style. Make it look like a still from a cel-shaded 3D game. Ensure atmospheric lighting is accurate to the style. Ensure painterly textures are displayed correctly. Keep in focus. The image is reminiscent of cel-shaded 3D adventure games."""

BONUS_PROMPT_STYLE_PIXEL_ART = """This is a pixel art scene with visible pixels. It features low-resolution subjects in a digital scene. The quality is exceptional. Pixel art style. Dot art aesthetic. Modify any subjects' appearance to match pixel art aesthetics. Make it look like a high-quality pixel art piece. Ensure digital lighting is accurate to the style. Ensure pixel-perfect textures are displayed correctly. Keep in focus. The image is reminiscent of the pixel art style."""

BONUS_PROMPT_STYLE_ANALOG_FILM = """This is an analog film photography scene with grain and vintage colors. It features real subjects in a candid scene. The quality is exceptional. Analog film style. Vintage photography aesthetic. Modify any subjects' appearance to match analog film aesthetics. Make it look like a developed film photo. Ensure natural lighting is accurate to the style. Ensure film grain and light leaks are displayed correctly. Keep in focus. The image is reminiscent of the analog film photography style."""

BONUS_PROMPT_STYLE_FAIRY_TALE = """This is a fairy tale themed artwork with whimsical details and soft, magical colors. It features storybook subjects in an enchanted scene. The quality is exceptional. Fairy tale art style. Children's book illustration aesthetic. Modify any subjects' appearance to match fairy tale aesthetics. Make it look like a page from a classic fairy tale. Ensure magical lighting is accurate to the style. Ensure soft, illustrative textures are displayed correctly. Keep in focus. The image is reminiscent of the fairy tale art style."""

BONUS_PROMPT_STYLE_GOTHIC = """This is a gothic themed artwork with dark atmosphere and intricate, somber details. It features ornate subjects in a mysterious scene. The quality is exceptional. Gothic art style. Dark romantic aesthetic. Modify any subjects' appearance to match gothic aesthetics. Make it look like a gothic masterpiece. Ensure moody lighting is accurate to the style. Ensure intricate stone and fabric textures are displayed correctly. Keep in focus. The image is reminiscent of the gothic art style."""

BONUS_PROMPT_STYLE_LOVECRAFTIAN = """This is a Lovecraftian themed artwork with cosmic horror elements and unsettling geometry. It features eldritch subjects in a madness-inducing scene. The quality is exceptional. Lovecraftian art style. Cosmic horror aesthetic. Modify any subjects' appearance to match Lovecraftian aesthetics. Make it look like an illustration from the Cthulhu Mythos. Ensure dark, oppressive lighting is accurate to the style. Ensure slimy and organic textures are displayed correctly. Keep in focus. The image is reminiscent of the Lovecraftian horror style."""

BONUS_PROMPT_STYLE_STAINED_GLASS = """This is a stained glass craftsmanship scene with vibrant colors and bold lead lines. It features glass subjects in a church window setting. The quality is exceptional. Stained glass art style. Mosaic aesthetic. Modify any subjects' appearance to match stained glass aesthetics. Make it look like a masterpiece of glasswork. Ensure backlit lighting is accurate to the style. Ensure glass textures are displayed correctly. Keep in focus. The image is reminiscent of the stained glass style."""

BONUS_PROMPT_STYLE_FILM_NOIR = """This is a film noir photography scene with high contrast black and white and dramatic shadows. It features film noir subjects in a moody urban scene. The quality is exceptional. Film noir art style. 1940s crime drama aesthetic. Modify any subjects' appearance to match film noir aesthetics. Make it look like a classic noir film frame. Ensure dramatic shadows are accurate to the style. Ensure monochrome textures are displayed correctly. Keep in focus. The image is reminiscent of the film noir style."""

BONUS_PROMPT_STYLE_CLAYMATION = """This is a claymation scene with visible fingerprints and plasticine textures. It features clay subjects in a handmade miniature scene. The quality is exceptional. Stop-motion animation style. Modify any subjects' appearance to match claymation aesthetics. Make it look like a still from a stop-motion movie. Ensure studio lighting is accurate to the style. Ensure clay textures are displayed correctly. Keep in focus. The image is reminiscent of the claymation style."""

BONUS_PROMPT_STYLE_ORIGAMI = """This is an origami paper craft scene with sharp creases and paper textures. It features folded paper subjects in a papercraft scene. The quality is exceptional. Origami art style. Folded paper aesthetic. Modify any subjects' appearance to match origami aesthetics. Make it look like a complex paper folding masterpiece. Ensure soft studio lighting is accurate to the style. Ensure paper grain textures are displayed correctly. Keep in focus. The image is reminiscent of the origami style."""

BONUS_PROMPT_STYLE_NEONPUNK = """This is a neonpunk scene with fluorescent colors and UV lighting. It features punk subjects in a glowing night scene. The quality is exceptional. Neonpunk art style. Blacklight aesthetic. Modify any subjects' appearance to match neonpunk aesthetics. Make it look like a glowing fluorescent masterpiece. Ensure UV lighting is accurate to the style. Ensure glowing textures are displayed correctly. Keep in focus. The image is reminiscent of the neonpunk style."""

BONUS_PROMPT_STYLE_GRAFFITI = """This is a photorealistic graffiti mural with spray paint textures and wall grunge. It features street art subjects on a concrete wall. The quality is exceptional. Street art style. Spray paint aesthetic. Modify any subjects' appearance to match graffiti aesthetics. Make it look like a high-quality mural. Ensure outdoor lighting is accurate to the style. Ensure dripping paint and concrete textures are displayed correctly. Keep in focus. The image is reminiscent of the graffiti art style."""

BONUS_PROMPT_STYLE_LOONEY_TUNES = """This is an animation frame in the classic cartoon style of Looney Tunes shorts, featuring exaggerated expressions and elastic anatomy. It features screwball subjects in a classic cartoon scene. The quality is exceptional. Classic slapstick cartoon aesthetic. Modify any subjects' appearance to match the classic slapstick cartoon animation style. Make it look like a still from a classic slapstick cartoon. Ensure bright flat colors are accurate to the style. Ensure dynamic ink lines are displayed correctly. Keep in focus. The image is reminiscent of classic slapstick cartoon style."""

BONUS_PROMPT_STYLE_NICKELODEON = """This is an animation frame in the 90s cartoon style of Nickelodeon shows, featuring quirky character designs and bold ink lines. It features 90s cartoon subjects in a playful scene. The quality is exceptional. Quirky 90s cartoon aesthetic. Modify any subjects' appearance to match the quirky 90s cartoon animation style. Make it look like a still from a quirky 90s cartoon. Ensure vibrant colors are accurate to the style. Ensure thick distinct outlines are displayed correctly. Keep in focus. The image is reminiscent of quirky 90s cartoon style."""

BONUS_PROMPT_STYLE_CARTOON_NETWORK = """This is an animation frame in the stylized mid-2000s cartoon style of Cartoon Network shows, featuring sharp outlines and stylized backgrounds. It features stylized subjects in a dynamic scene. The quality is exceptional. Stylized mid-2000s cartoon aesthetic. Modify any subjects' appearance to match the stylized mid-2000s cartoon animation style with thick outlines and flat shading. Make it look like a still from a mid-2000s cartoon show. Ensure flat colors are accurate to the style. Ensure sharp clean lines are displayed correctly. Keep in focus. The image is reminiscent of stylized mid-2000s cartoon style."""

BONUS_PROMPT_STYLE_ADULT_SWIM = """This is an animation frame in the alternative animation style of Adult Swim shows, featuring unique visual aesthetics and surreal scenes. It features late-night cartoon subjects in a surreal scene. The quality is exceptional. Alternative surreal animation aesthetic. Modify any subjects' appearance to match the alternative surreal animation style. Make it look like a still from an alternative animated show. Ensure flat lighting is accurate to the style. Ensure specific animation textures are displayed correctly. Keep in focus. The image is reminiscent of alternative surreal animation style."""

BONUS_PROMPT_STYLE_ADVENTURE_TIME = """This is an animation frame in the whimsical cartoon style of the animated series Adventure Time, featuring thin, consistent line work. It features whimsical subjects in a whimsical, colorful scene. The quality is exceptional. Whimsical Adventure Time aesthetic. Modify any subjects' appearance to match the whimsical cartoon style of the animated series Adventure Time. Make it look like a still from the animated series Adventure Time. Ensure bright, happy lighting is accurate to the style. Ensure thin, consistent lines are displayed correctly. Keep in focus. The image is reminiscent of the Adventure Time animation style."""

BONUS_PROMPT_STYLE_DRAGON_BALL_Z = """This is an animation frame in the shonen anime style of the anime series Dragon Ball Z, featuring intense expressions and dramatic shading. It features any subjects in a dynamic scene. The quality is exceptional. Shonen anime Dragon Ball Z aesthetic. Modify any subjects' appearance to match the shonen anime style of the anime series Dragon Ball Z. Make it look like a still from the anime series Dragon Ball Z. Ensure dramatic lighting is accurate to the style. Ensure sharp shadows and action lines are displayed correctly. Keep in focus. The image is reminiscent of the Dragon Ball Z anime style."""

BONUS_PROMPT_STYLE_COWBOY_BEBOP = """This is an animation frame in the noir anime style of the anime series Cowboy Bebop, featuring cinematic composition and realistic proportions. It features any subjects in a dynamic scene. The quality is exceptional. Noir anime Cowboy Bebop aesthetic. Modify any subjects' appearance to match the noir anime style of the anime series Cowboy Bebop. Make it look like a still from the anime series Cowboy Bebop. Ensure cinematic lighting is accurate to the style. Ensure high-quality cel shading is displayed correctly. Keep in focus. The image is reminiscent of the Cowboy Bebop anime style."""

BONUS_PROMPT_STYLE_RICK_AND_MORTY = """This is an animation frame in the sci-fi cartoon style of the animated series Rick and Morty, featuring relaxed, rounded anatomy. It features any subjects in a chaotic scene. The quality is exceptional. Sci-fi cartoon Rick and Morty aesthetic. Modify any subjects' appearance to match the sci-fi cartoon style of the animated series Rick and Morty. Make it look like a still from the animated series Rick and Morty. Ensure flat colors are accurate to the style. Ensure distinctively stylized pupils are displayed correctly. Keep in focus. The image is reminiscent of the Rick and Morty animation style."""

BONUS_PROMPT_STYLE_BOBS_BURGERS = """This is an animation frame in the animated sitcom style of the animated series Bob's Burgers, featuring thick outlines and distinct tubular anatomy. It features any subjects in a city scene. The quality is exceptional. Animated sitcom Bob's Burgers aesthetic. Modify any subjects' appearance to match the animated sitcom style of the animated series Bob's Burgers. Make it look like a still from the animated series Bob's Burgers. Ensure flat colors are accurate to the style. Ensure distinct animated sitcom tubular anatomy is displayed correctly. Keep in focus. The image is reminiscent of the Bob's Burgers animation style."""

BONUS_PROMPT_STYLE_GRAVITY_FALLS = """This is an animation frame in the mystery cartoon style of the animated series Gravity Falls, featuring appealing cartoon anatomy and smooth line art. It features any subjects in a forest scene. The quality is exceptional. Mystery cartoon Gravity Falls aesthetic. Modify any subjects' appearance to match the mystery cartoon style of the animated series Gravity Falls. Make it look like a still from the animated series Gravity Falls. Ensure atmospheric lighting is accurate to the style. Ensure smooth lines and specific eye shapes are displayed correctly. Keep in focus. The image is reminiscent of the Gravity Falls animation style."""

BONUS_PROMPT_STYLE_SAILOR_MOON = """This is an animation frame in the magical girl anime style of the anime series Sailor Moon, featuring large expressive eyes and elongated limbs. It features any subjects in a magical scene. The quality is exceptional. Magical girl anime Sailor Moon aesthetic. Modify any subjects' appearance to match the magical girl anime style of the anime series Sailor Moon. Make it look like a still from the anime series Sailor Moon. Ensure soft, dreamy lighting is accurate to the style. Ensure pastel colors are displayed correctly. Keep in focus. The image is reminiscent of the Sailor Moon anime style."""

BONUS_PROMPT_STYLE_CCTV_EDIT = """This is a CCTV security camera scene with digital noise and a low-quality recording aesthetic. It features real subjects in a surveillance scene. The quality is exceptional. CCTV footage style. Security camera aesthetic. Modify any subjects' appearance to match surveillance aesthetics. Make it look like a still from a security recording. Ensure harsh artificial lighting is accurate to the style. Ensure a grainy monitoring perspective is displayed correctly. Keep in focus. The image is reminiscent of the CCTV security camera style."""

BONUS_PROMPT_STYLE_CCTV_RAW = """This is a CCTV security camera scene with digital noise and a low-quality recording aesthetic. It features real subjects in a surveillance scene. The quality is exceptional. CCTV footage style. Security camera aesthetic. Make it look like a still from a security recording. Ensure harsh artificial lighting is accurate to the style. Ensure a grainy monitoring perspective is displayed correctly. Keep in focus. The image is reminiscent of the CCTV security camera style."""

BONUS_PROMPT_STYLE_POLAROID = """This is a Polaroid instant film photograph with high level of detail. It features vintage camera subjects in a nostalgic scene. The quality is characteristic of 1970s-80s instant film. Polaroid art style. Instant film aesthetic. Warm color cast, faded tones, soft focus. Modify any subjects' appearance to show Polaroid details. Make it look like a vintage Polaroid snapshot. Ensure warm, desaturated colors are accurate. Ensure faded edges and vignetting are displayed correctly. Keep in focus. High quality Polaroid instant film art."""

BONUS_PROMPT_STYLE_GLITCH_ART = """This is glitch art with high level of intentional digital corruption. It features subjects distorted by pixel displacement and color channel errors. The quality emphasizes digital artifacts as aesthetic elements. Glitch art style. Digital corruption aesthetic. Color separation, scanlines, pixel displacement. Modify any subjects' appearance to show glitch effects. Make it look like intentional digital art. Ensure RGB channel misalignment is accurate. Ensure data corruption artifacts are displayed prominently. Keep in focus. High quality glitch art."""

BONUS_PROMPT_STYLE_PIXEL_ART = """This is pixel art with high level of retro aesthetic detail. It features subjects rendered in blocky pixels with limited color palettes. The quality is characteristic of 16-bit video game graphics. Pixel art style. Retro arcade aesthetic. Limited colors, dithering, blocky forms. Modify any subjects' appearance to show pixel details. Make it look like a retro video game screenshot. Ensure pixelated edges are accurate. Ensure indexed color palette is displayed correctly. Keep in focus. High quality pixel art."""

BONUS_PROMPT_STYLE_WATERCOLOR = """This is a watercolor painting with high level of artistic detail. It features subjects rendered in soft, translucent washes. The quality is characteristic of fine watercolor art on quality paper. Watercolor art style. Paint and paper aesthetic. Soft color bleeding, transparent layers, paper texture. Modify any subjects' appearance to show watercolor details. Make it look like a fine watercolor masterpiece. Ensure color bleeding and diffusion are accurate. Ensure visible paper texture is displayed correctly. Keep in focus. High quality watercolor art."""

BONUS_PROMPT_STYLE_KODACHROME = """This is a Kodachrome color film photograph with high level of detail. It features subjects captured on classic color slide film from the golden age of photography. The quality is exceptional and characteristic of 1950s-70s Kodachrome stock. Kodachrome art style. Classic color film aesthetic. Rich saturated colors, warm tones, vibrant palette. Modify any subjects' appearance to show Kodachrome details. Make it look like a vintage Kodachrome slide. Ensure warm, saturated colors are accurate. Ensure distinctive color rendering is displayed correctly. Keep in focus. High quality Kodachrome film art."""

BONUS_PROMPT_STYLE_GRAPHIC_NOVEL = """This is a graphic novel illustration with high level of artistic detail. It features subjects rendered in professional comic book panel style. The quality is exceptional and characteristic of modern graphic novels. Graphic novel art style. Professional comic book aesthetic. Bold ink work, dramatic lighting, expressive line art. Modify any subjects' appearance to show graphic novel details. Make it look like a professional graphic novel page. Ensure bold ink lines are accurate. Ensure dramatic composition and dynamic poses are displayed correctly. Keep in focus. High quality graphic novel art."""

BONUS_PROMPT_STYLE_CEL_SHADED = """This is cel-shaded video game art with high level of stylized detail. It features subjects rendered with hand-drawn illustration style in 3D. The quality is exceptional and characteristic of cel-shading techniques. Cel-shaded art style. Hand-drawn 3D aesthetic. Thick outlines, flat colors, bold shadows. Modify any subjects' appearance to show cel-shaded details. Make it look like a cel-shaded video game screenshot. Ensure thick black outlines are accurate. Ensure flat color blocks and simplified shading are displayed correctly. Keep in focus. High quality cel-shaded art."""

BONUS_PROMPT_STYLE_VIDEO_GAME = """This is a video game render with high level of game engine detail. It features subjects rendered in standard 3D video game graphics. The quality is exceptional and characteristic of modern game engines. Video game art style. Game engine aesthetic. Clean geometry, realistic proportions, game textures. Modify any subjects' appearance to show video game details. Make it look like a professional video game screenshot. Ensure game engine shaders are accurate. Ensure balanced lighting and material rendering are displayed correctly. Keep in focus. High quality video game art."""

BONUS_PROMPT_STYLE_SKYRIM = """This is a scene in the medieval fantasy RPG style of The Elder Scrolls video games, featuring classic fantasy textures and game engine rendering. It features fantasy subjects in a medieval RPG scene. The quality is exceptional and characteristic of gritty medieval fantasy RPG engine graphics. Medieval fantasy RPG art style. Medieval fantasy aesthetic. Medieval textures, fantasy proportions, game engine rendering. Modify any subjects' appearance to match the gritty medieval fantasy RPG engine graphics. Make it look like a still from a medieval fantasy RPG video game. Ensure classic fantasy textures are accurate. Ensure medieval Nordic atmosphere and game engine lighting are displayed correctly. Keep in focus. High quality fantasy RPG art."""

BONUS_PROMPT_STYLE_CLAYMATION_DETAILED = """This is a stop-motion clay animation render with high level of detail. It features stop-motion clay subjects in a handmade scene. The quality is exceptional. Claymation art style. Stop-motion animation aesthetic. Tactile clay textures, visible seams, handcrafted quality. Modify any subjects' appearance to show claymation details. Make it look like a professional stop-motion film screenshot. Ensure clay textures are accurate. Ensure visible joint articulations are displayed correctly. Keep in focus. High quality claymation art."""

BONUS_PROMPT_STYLE_CLAYMATION_SIMPLIFIED = """This is a low-detail stop-motion clay animation render with clean, basic details. It features low-detail stop-motion clay subjects in a minimalist scene. The quality is characteristic of simplified stop-motion animation. Simplified claymation art style. Basic stop-motion animation aesthetic. Smooth clay forms, simple shapes, minimal texture. Modify any subjects' appearance to show simplified claymation details. Make it look like a simple stop-motion animation screenshot. Ensure smooth, featureless clay surfaces are accurate. Ensure basic joint articulations are displayed correctly. Keep in focus. Simplified claymation art."""

BONUS_PROMPT_STYLE_SIMS = """This is a scene in the vibrant 3D life simulation style of The Sims video games, featuring cheerful saturated colors and clean stylized geometry. It features life simulation subjects in a stylized scene. The quality is exceptional. Stylized 3D life simulation game art style. Life simulation game aesthetic. Vibrant, cheerful, whimsical atmosphere. Modify any subjects' appearance to match the stylized 3D life simulation game graphics. Make it look like a professional game screenshot. Ensure bright saturated colors are accurate. Ensure smooth stylized geometry is displayed correctly. Keep in focus. High quality life simulation game art."""

BONUS_PROMPT_STYLE_STEAMPUNK = """This is a steampunk scene with high level of detail. It features Victorian industrial subjects in a mechanical scene. The quality is exceptional. Steampunk art style. Victorian industrial aesthetic. Brass gears, clockwork details, warm sepia tones. Modify any subjects' appearance to show steampunk details. Make it look like a steampunk masterpiece. Ensure brass and copper textures are accurate. Ensure mechanical elements are prominently displayed. Keep in focus. High quality steampunk art."""

BONUS_PROMPT_STYLE_HORROR_MOVIE = """This is a scene in the cinematic horror movie style, featuring desaturated color grading, dramatic shadows, and oppressive atmosphere. It features horror subjects in a frightening scene. The quality is exceptional. Horror movie style. Cinematic horror aesthetic. Dark lighting, eerie mood, supernatural dread. Modify any subjects' appearance to match horror movie aesthetics. Make it look like a still from a horror film. Ensure dim, ominous lighting is accurate to the style. Ensure desaturated colors and fog or mist effects are displayed correctly. Keep in focus. High quality horror movie art."""

BONUS_PROMPT_STYLE_PS1 = """This is a scene in the low-polygon 3D video game style of early PlayStation video games, featuring blocky geometry, pixelated textures, and flat shading. It features retro subjects in a 3D scene. The quality is characteristic of early console graphics. Retro 32-bit low-polygon 3D graphics style. Classic 3D gaming aesthetic. Low-polygon models, pixelated textures, flat shading. Modify any subjects' appearance to match early 3D game aesthetics. Make it look like a still from a retro 32-bit low-polygon 3D video game. Ensure low-polygon geometry is accurate to the style. Ensure pixelated textures and flat-shaded surfaces are displayed correctly. Keep in focus. High quality retro 3D video game art."""

BONUS_PROMPT_STYLE_70S_SCIFI = """This is a scene in the retro-futuristic style of 1970s science fiction cinema, featuring practical set design, vintage color grading, and film grain aesthetic. It features retro-futuristic subjects in a 70s sci-fi scene. The quality is characteristic of 1970s film production. 70s sci-fi movie style. Vintage futurism aesthetic. Practical effects, film grain, vintage color grading. Modify any subjects' appearance to match 1970s sci-fi aesthetics. Make it look like a still from a classic 70s science fiction film. Ensure film grain and vintage color grading are accurate to the style. Ensure practical effects and hand-crafted construction details are displayed correctly. Keep in focus. High quality 70s science fiction movie art."""

BONUS_PROMPT_STYLE_INFLATED = """This is an inflatable balloon art scene with high level of material detail. It features subjects transformed into fully inflated, air-filled balloon versions of themselves. The quality is exceptional. Inflated balloon style. Shiny elastic vinyl aesthetic. Taut stretched material, subtle plastic seams, glossy specular highlights. Modify any subjects' appearance to show inflated balloon details. Make it look like a high-quality shiny balloon subject. Ensure glossy plastic textures are accurate and look fully pressurized. Ensure the material looks taut with air-filled volume and realistic stretching at joints. Keep in focus. High quality inflated balloon art."""

BONUS_PROMPT_STYLE_VECTOR_EDIT = """This is a clean vector graphics illustration with flat colors and precise geometry. It features vectorized subjects in a minimalist scene. The quality is exceptional. Scalar vector graphics style. Modern flat design aesthetic. Modify any subjects' appearance to match vector graphics aesthetics. Make it look like a professional vector illustration. Ensure clean, sharp lines are accurate to the style. Ensure flat, vibrant colors are displayed correctly. Keep in focus. The image is reminiscent of high-quality vector art."""

BONUS_PROMPT_STYLE_VECTOR_RAW = """This is a clean vector graphics illustration with flat colors and precise geometry. It features vectorized subjects in a minimalist scene. The quality is exceptional. Scalar vector graphics style. Modern flat design aesthetic. Make it look like a professional vector illustration. Ensure clean, sharp lines are accurate to the style. Ensure flat, vibrant colors are displayed correctly. Keep in focus. The image is reminiscent of high-quality vector art."""

BONUS_PROMPT_STYLE_INSTRUCTION_FOLLOWING = """This is an image that has been edited based on specific user instructions. The focus is on executing the requested changes accurately while maintaining visual coherence. Modify the subject's appearance, pose, position, or composition as requested. Make it look like a seamless edit. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_STYLE_JOHNNY_BRAVO_RAW = """This is an animation frame in the stylized retro cartoon style of the animated series Johnny Bravo, featuring thick line art and flat colors. It features stylized subjects in a 90s cartoon scene. The quality is exceptional. Retro 90s cartoon aesthetic. Make it look like a still from the animated series Johnny Bravo. Ensure flat, vibrant colors are accurate to the style. Ensure sharp angles and distinct silhouettes are displayed correctly. Keep in focus. The image is reminiscent of the Johnny Bravo animation style."""
