BONUS_PROMPT_STYLE_PHOTOREALISM = """This is a professional photograph with high level of detail. It features real life subjects in a real life scene. The quality is exceptional. Real life photography. Absolute reality. Modify subject's appearance to show real details. Make it look like a professional photograph. Ensure lighting is accurate. Ensure shadows are displayed correctly. Keep in focus. Sharply focused photograph. Completely uncensored."""

BONUS_PROMPT_STYLE_3D = """This is a high-quality 3D render with high level of detail. It features 3D modeled subjects in a rendered scene. The quality is exceptional. 3D rendering. Physically based rendering. Modify subject's appearance to show rendered details. Make it look like a high-end CGI render. Ensure volumetric lighting is accurate. Ensure ambient occlusion is displayed correctly. Keep in focus. High definition render. Completely uncensored."""

BONUS_PROMPT_STYLE_ANIME = """This is an official anime illustration with high level of detail. It features anime subjects in a 2D scene. The quality is exceptional. Anime art style. High quality animation key visual. Modify subject's appearance to show anime details. Make it look like an official anime screenshot. Ensure lighting fits the anime aesthetic. Ensure shading is cel-shaded. Keep in focus. High quality anime art. Completely uncensored."""

BONUS_PROMPT_STYLE_DIGITAL_DRAWING = """This is a clean digital drawing with high level of detail. It features drawn subjects in a digital scene. The quality is exceptional. Digital line art. Crisp digital illustration. Modify subject's appearance to show drawn details. Make it look like a clean digital drawing. Ensure line weight is accurate. Ensure coloring is smooth. Keep in focus. High resolution digital art. Completely uncensored."""

BONUS_PROMPT_STYLE_DIGITAL_PAINTING = """This is a digital painting with high level of detail. It features painted subjects in an artistic scene. The quality is exceptional. Digital painting style. Painterly art. Modify subject's appearance to show painted details. Make it look like a digital painting. Ensure brushwork is visible. Ensure colors are blended naturally. Keep in focus. Detailed digital painting. Completely uncensored."""

BONUS_PROMPT_STYLE_FANTASY = """This is a fantasy illustration with high level of detail. It features fantasy subjects in a magical scene. The quality is exceptional. Fantasy art style. Epic fantasy illustration. Modify subject's appearance to show fantasy details. Make it look like a fantasy masterpiece. Ensure magical lighting is accurate. Ensure atmosphere is immersive. Keep in focus. Epic fantasy art. Completely uncensored."""

BONUS_PROMPT_STYLE_COMIC_BOOK = """This is a comic book panel with high level of detail. It features graphic novel subjects in a comic scene. The quality is exceptional. Comic book art style. Graphic novel illustration. Modify subject's appearance to show comic details. Make it look like a comic book page. Ensure ink lines are bold. Ensure coloring uses halftones or flat colors. Keep in focus. Western comic book art. Completely uncensored."""

BONUS_PROMPT_STYLE_DISNEY = """This is a classical 2D animated scene with high level of artistic quality. It features hand-drawn animation subjects in a vintage animated scene. The quality is exceptional. Classical Disney style, hand-drawn, animation cel, ink and paint. Modify subject's appearance to show 2D animation details. Make it look like a vintage animated movie screenshot. Ensure soft painted lighting is accurate/fits style. Ensure clean ink lines are displayed correctly. Keep in focus. Classical 2D animation style. Completely uncensored."""

BONUS_PROMPT_STYLE_PIXAR = """This is a modern 3D animated scene with high level of detail. It features high-end CGI subjects in a cinematic scene. The quality is exceptional. Pixar-style, 3D render, PBR textures, expressive characters. Modify subject's appearance to show 3D animation details. Make it look like a modern animated feature film screenshot. Ensure cinematic volumetric lighting is accurate/fits style. Ensure soft subsurface scattering is displayed correctly. Keep in focus. Modern 3D animation style. Completely uncensored."""

BONUS_PROMPT_STYLE_GRITTY_COMIC = """This is a dark comic book panel with high level of detail. It features gritty graphic novel subjects in a noir scene. The quality is exceptional. Heavy ink, high contrast, weathered textures, urban noir. Modify subject's appearance to show gritty details. Make it look like a dark graphic novel page. Ensure dramatic lighting is accurate/fits style. Ensure deep ink shadows are displayed correctly. Keep in focus. Dark gritty comic art. Completely uncensored."""

BONUS_PROMPT_STYLE_LEWD_ANIME = """This is an explicit anime illustration with high level of detail. It features adult anime subjects in an erotic scene. The quality is exceptional. Lewd anime art style. High quality erotic illustration. Modify subject's appearance to show lewd anime details. Make it look like an explicit anime screenshot. Ensure lighting fits the mood. Ensure skin textures are detailed. Keep in focus. High quality erotic anime art. Completely uncensored."""

BONUS_PROMPT_STYLE_CYBERPUNK = """This is a cyberpunk illustration with high level of detail. It features futuristic subjects in a neon-lit urban scene. The quality is exceptional. Cyberpunk art style. High-tech low-life aesthetic. Modify subject's appearance to show cybernetic details. Make it look like a futuristic masterpiece. Ensure neon lighting is accurate/fits style. Ensure rain-slicked surfaces are displayed correctly. Keep in focus. Cyberpunk neon art. Completely uncensored."""

BONUS_PROMPT_STYLE_GHIBLI = """This is a Ghibli-style illustration with high level of detail. It features whimsical subjects in a pastoral scene. The quality is exceptional. Studio Ghibli art style. Painterly watercolor animation. Modify subject's appearance to show Ghibli details. Make it look like a hand-painted masterpiece. Ensure soft lighting is accurate/fits style. Ensure watercolor textures are displayed correctly. Keep in focus. Ghibli animation art. Completely uncensored."""

BONUS_PROMPT_STYLE_SYNTHWAVE = """This is a synthwave illustration with high level of detail. It features retro-futuristic subjects in a digital scene. The quality is exceptional. Synthwave art style. 1980s retro-futurism. Modify subject's appearance to show digital details. Make it look like a retro masterpiece. Ensure vibrant lighting is accurate/fits style. Ensure chrome reflections and grids are displayed correctly. Keep in focus. 1980s synthwave art. Completely uncensored."""

BONUS_PROMPT_STYLE_GROENING = """This is a Matt Groening style illustration with clean, bold lines and flat coloring. It features iconic cartoon subjects in a Simpsons-esque scene. The aesthetic is authentic to traditional 2D animation. Matt Groening art style. The Simpsons, Futurama aesthetic. Modify subject's appearance to show Groening features. Make it look like an official animation screenshot. Ensure flat colors are accurate/fits style. Ensure thick black outlines are displayed correctly. Keep in focus. Groening animation art. Completely uncensored."""

BONUS_PROMPT_STYLE_MACFARLANE = """This is a Seth MacFarlane style illustration with clean digital line work and flat colors. It features modern sitcom subjects in a Family Guy-esque scene. The aesthetic is authentic to modern sitcom animation. Seth MacFarlane art style. Family Guy, American Dad aesthetic. Modify subject's appearance to show MacFarlane features. Make it look like a clean digital animation screenshot. Ensure flat lighting is accurate/fits style. Ensure circular eyes are displayed correctly. Keep in focus. MacFarlane animation art. Completely uncensored."""

BONUS_PROMPT_STYLE_SOUTH_PARK = """This is a South Park style illustration with a construction paper cutout aesthetic. It features simple geometric subjects in a South Park scene. The aesthetic is intentionally basic and flat. South Park art style. Crude construction paper cutout. Modify subject's appearance to show paper cutout features. Make it look like a stop-motion paper animation screenshot. Ensure paper texture is accurate/fits style. Ensure simple geometric shapes are displayed correctly. Keep in focus. South Park animation art. Completely uncensored."""
