BONUS_PROMPT_EDIT_TARGET_GENERAL_SUBJECT = """The edit focuses on the general subject in the image. Modify the subject's appearance, pose, position, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_HUMAN_FEMALE = """The edit focuses on the female human in the image. Modify her appearance, pose, position, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_HUMAN_MALE = """The edit focuses on the man in the image. Modify his appearance, pose, position, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_HUMAN_SHEMALE = """The edit focuses on the curvaceous transgender female with a feminine appearance in the image. Modify their appearance, pose, position, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_HUMAN_FEMBOY = """The edit focuses on the small skinny male subject with girly features in the image. Modify their appearance, pose, position, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_HUMAN_GROUP = """The edit focuses on the group of humans in the image. Modify their appearance, pose, position, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_ANTHRO_FEMALE = """The edit focuses on the female anthropomorphic subject in the image. Modify her appearance, pose, position, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_ANTHRO_MALE = """The edit focuses on the male anthropomorphic subject in the image. Modify his appearance, pose, position, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_ANTHRO_SHEMALE = """The edit focuses on the curvaceous transgender anthropomorphic feminine subject in the image. Modify their appearance, pose, position, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_ANTHRO_FEMBOY = """The edit focuses on the small skinny transgender anthropomorphic male subject with girly features in the image. Modify their appearance, pose, position, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_ANTHRO_GROUP = """The edit focuses on the group of anthropomorphic subjects in the image. Modify their appearance, pose, position, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_INDOOR_SETTING = """The edit focuses on the indoor environment. Modify the room's layout, furniture, lighting, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_OUTDOOR_SETTING = """The edit focuses on the outdoor environment. Modify the landscape, weather, lighting, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_ADVERT_OBJECT = """The edit focuses on the promotional object in the image. Modify the product's appearance, positioning, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_MECHANICAL_OBJECT = """The edit focuses on the mechanical object in the image. Modify the machinery's appearance, positioning, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_ROBOTIC_OBJECT = """The edit focuses on the robotic object in the image. Modify the robot's appearance, positioning, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_SEX_TOY_OBJECT = """The edit focuses on the adult toy in the image. Modify its appearance, positioning, or composition as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_LIGHTING_EFFECT = """The edit focuses on the lighting effects in the image. Modify the light sources, intensity, color, or direction as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_SHADOWS_EFFECT = """The edit focuses on the shadows in the image. Modify the shadow density, orientation, or distribution as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_TEXTURE_PROPERTY = """The edit focuses on the texture of a surface in the image. Modify the material properties, roughness, or patterns as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_SKIN_PROPERTY = """The edit focuses on the skin texture and appearance. Modify the skin's detail, smoothness, or properties as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""

BONUS_PROMPT_EDIT_TARGET_SURFACE_PROPERTY = """The edit focuses on the properties of a specific surface. Modify its reflective, refractive, or material characteristics as requested while maintaining visual coherence. Ensure the changes are integrated naturally into the scene. Ensure the new elements or changes respect the visual context. Keep the unedited parts in focus. The image is a faithful execution of the editing request."""
