INSTRUCT_PROMPT_EDIT_OP_INCREASE_DETAIL = """Keep pose. Keep angle. Keep viewing direction. Increase the level of visual detail on the targeted element. Add intricate textures, fine surface features, and complex patterns as requested. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure the new details are integrated naturally and follow the visual logic of the scene. Make it more detailed. Add more fine details. Prioritize the request to add detail while keeping unedited areas in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate more detailed version of the target."""

INSTRUCT_PROMPT_EDIT_OP_DECREASE_DETAIL = """Keep pose. Keep angle. Keep viewing direction. Decrease the level of visual detail on the targeted element. Simplify textures, smooth out fine features, and reduce complexity for a cleaner look. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure the simplification respects the visual context and maintains the core form. Make it simpler. Reduce surface details. Prioritize the request to reduce detail while keeping unedited areas in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate simplified version of the target."""

INSTRUCT_PROMPT_EDIT_OP_MOSAIC_CENSOR = """Keep pose. Keep angle. Keep viewing direction. Apply a mosaic pixelation effect to censor the targeted area. Ensure the pixelation is dense enough to obscure details while following the shape of the target. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Integrate the mosaic effect seamlessly into the image context. Apply mosaic censorship. Hide the target with pixelation. Prioritize the censorship request while keeping the rest of the image unedited and in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate censored version with mosaic effects."""

INSTRUCT_PROMPT_EDIT_OP_BLACK_BAR_CENSOR = """Keep pose. Keep angle. Keep viewing direction. Apply solid black bars to censor the targeted area. Ensure the bars are positioned precisely to obscure the intended content. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Maintain the overall composition of the image while prioritizing the censorship request. Add black censorship bars. Obscure the target with black bars. Keep unedited areas in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate censored version with black bars."""

INSTRUCT_PROMPT_EDIT_OP_REMOVE_CENSORSHIP = """Keep pose. Keep angle. Keep viewing direction. Remove any censorship elements, such as mosaic pixelation or black bars, from the targeted area. Reconstruct the underlying details realistically and seamlessly based on the surrounding context. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure the revealed content is anatomically correct and visually coherent. Remove the censorship. Reveal the hidden parts. Prioritize the removal of censorship while keeping the rest of the image in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate decensored version with revealed details."""

INSTRUCT_PROMPT_EDIT_OP_DECENSOR_MOSAIC = """Keep pose. Keep angle. Keep viewing direction. Specifically target and remove mosaic pixelation from the image. Reconstruct the obscured details with high fidelity and realistic textures. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure the reconstruction follows the visual logic and anatomy of the subject. Remove mosaic pixelation. Clear the pixelated area. Prioritize decensoring the mosaic while keeping unedited areas in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate decensored version with clear details."""

INSTRUCT_PROMPT_EDIT_OP_INCREASE_MUSCLES = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's physique to increase muscular definition and mass. Enhance the visibility of muscle groups, such as biceps, pectorals, and abdominals, as requested. Ensure the changes are anatomically plausible and integrated naturally into the subject's pose. Increase muscularity. Make the subject more muscular and defined. Prioritize the muscle enhancement while keeping the subject's identity and the background intact. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate more muscular version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_UNDEFINED_BODY = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's body to have a less defined or more ambiguous shape. Soften muscular definition and simplify body contours while maintaining the overall silhouette. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure the changes are integrated naturally. Make the body less defined. Soften the subject's form. Prioritize the request for an undefined body shape while keeping the rest of the image in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate less defined version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_SLENDER = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's body to appear more slender and lean. Adjust the proportions to be thinner while maintaining a healthy and aesthetic appearance. Ensure the changes are integrated naturally into the pose and composition. Make it slender. Slim down the subject. Prioritize the slenderizing edit while keeping the subject's identity intact. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate more slender version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_SKINNY = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's body to appear significantly thinner and skinnier. Reduce body mass and emphasize a lean, thin frame. Ensure the changes are integrated naturally and respect the visual context. Make it skinny. Thin out the subject considerably. Prioritize the request to make the subject skinny while keeping unedited areas in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate skinny version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_ANOREXIC = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's body to appear extremely thin and underweight, reflecting an anorexic physique. Emphasize bony structures and minimal body fat as requested. Ensure the changes are integrated naturally into the scene. Make it look anorexic. Emphasize an extremely thin frame. Prioritize the request while maintaining visual coherence in unedited areas. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate anorexic version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_FEMININE = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's appearance and features to be more feminine. Soften facial features, adjust body proportions, and enhance feminine traits as requested. Ensure the changes are integrated naturally and maintain the subject's core identity. Make it feminine. Add feminine traits. Prioritize the feminizing edit while keeping the rest of the scene intact. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate more feminine version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_VOLUPTUOUS = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's body to appear more voluptuous and curvy. Enhance specific curves and proportions as requested while maintaining a balanced and aesthetic look. Ensure the changes are integrated naturally into the pose. Make it voluptuous. Enhance the subject's curves. Prioritize the request for a voluptuous figure while keeping unedited areas in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate more voluptuous version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_OBESE = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's body to appear significantly heavier and obese. Increase body mass and adjust proportions to reflect a high level of body fat. Ensure the changes are integrated naturally into the composition. Make it obese. Increase body weight and fat. Prioritize the request to make the subject obese while keeping the background intact. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate obese version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_OLDER = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's appearance to look significantly older and mature. Add rougher skin features, aging skin details, and adjust features to reflect a mature age. Ensure natural looking aging features and keep the subject's identity. Make subject look older. Age the subject's features. Prioritize the aging edit while keeping the rest of the image in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate older version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_YOUNGER = """Keep angle. Keep viewing direction. Modify the subject's appearance to look significantly younger and youthful. Smoother skin, brighten features, and adjust proportions to reflect a youthful age. Ensure natural looking young looking features and keep the subject's identity. Make subject look younger. Rejuvenate the subject's features. Prioritize the youthful edit while keeping the rest of the scene intact. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate younger version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_PRETTY = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's appearance to be more aesthetically pleasing and pretty. Enhance facial symmetry, clarify features, and adjust proportions for a more attractive look. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure the changes are subtle and maintain the subject's identity. Make it look pretty. Enhance the subject's beauty. Prioritize the request for prettiness while keeping unedited areas in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate prettier version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_BEAUTIFUL = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's appearance to be exceptionally beautiful. Enhance features, skin quality, and overall aesthetic appeal to a high standard. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure the beauty enhancement is integrated naturally and maintains the subject's core identity. Make it look beautiful. Enhance the subject's overall appeal. Prioritize the request for beauty while keeping the rest of the scene intact. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate beautiful version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_SEXY = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's appearance, pose, or expression to be more sexually appealing and sexy. Enhance attractive traits and adjust the composition to emphasize allure. Ensure the changes are integrated naturally and follow the requested level of provocativeness. Make it look sexy. Enhance the subject's allure. Prioritize the sexy edit while keeping unedited areas in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate sexier version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_SLUTTY = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's appearance and attire to be highly provocative and sexually suggestive. Emphasize revealing clothing, seductive expressions, and a bold, slutty aesthetic as requested. Ensure the changes are integrated naturally into the scene. Make it look slutty. Emphasize provocative features and clothing. Prioritize the request while maintaining visual coherence in unedited areas. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate more slutty version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_VIRTUOUS = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's appearance and expression to look virtuous, modest, and pure. Adjust attire and features to convey a sense of innocence and high moral character. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure the changes are integrated naturally and follow the visual context. Make it look virtuous. Add modest and pure traits. Prioritize the virtuous edit while keeping unedited areas in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate more virtuous version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_MAKE_CHASTE = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's appearance and clothing to be chaste and conservative. Ensure the attire is modest and covers the body appropriately. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Adjust expressions to be reserved and decent. Make it look chaste. Change to modest and conservative dress. Prioritize the chaste edit while keeping the rest of the image intact. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be an accurate more chaste version of the subject."""

INSTRUCT_PROMPT_EDIT_OP_DRESS_CLOTHES = """Keep pose. Keep angle. Keep viewing direction. Change the subject's attire to standard everyday clothes. Ensure the clothing fits the subject's pose and the scene's context naturally. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Maintain the subject's identity while prioritizing the change in dress. Dress in clothes. Change outfit to everyday attire. Keep unedited areas in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be the subject in regular clothes."""

INSTRUCT_PROMPT_EDIT_OP_DRESS_BIKINI = """Keep pose. Keep angle. Keep viewing direction. Change the subject's attire to a bikini. Ensure the bikini's design and fit are integrated naturally onto the subject's body and pose. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Maintain visual coherence and prioritize the requested outfit change while keeping unedited areas in focus. Dress in a bikini. Change outfit to a bikini. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be the subject in a bikini."""

INSTRUCT_PROMPT_EDIT_OP_DRESS_MICROKINI = """Keep pose. Keep angle. Keep viewing direction. Change the subject's attire to a microkini. Ensure the minimal coverage of the microkini is represented accurately and fits the subject's body naturally. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Maintain the scene's logic while prioritizing the microkini edit. Dress in a microkini. Change outfit to a microkini. Keep unedited areas in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be the subject in a microkini."""

INSTRUCT_PROMPT_EDIT_OP_DRESS_GOWN = """Keep pose. Keep angle. Keep viewing direction. Change the subject's attire to an elegant gown. Ensure the gown's fabric, drape, and design are integrated naturally into the subject's pose and the environment. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Prioritize the gown edit while keeping the rest of the image in focus. Dress in a gown. Change outfit to an elegant gown. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be the subject in a gown."""

INSTRUCT_PROMPT_EDIT_OP_DRESS_FORMAL = """Keep pose. Keep angle. Keep viewing direction. Change the subject's attire to formal wear, such as a suit or evening dress. Ensure the formal clothing is well-fitted and appropriate for the subject's pose. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Prioritize the formal dress edit while keeping unedited areas in focus. Dress in formal wear. Change outfit to formal attire. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be the subject in formal dress."""

INSTRUCT_PROMPT_EDIT_OP_DRESS_KINKY = """Keep pose. Keep angle. Keep viewing direction. Change the subject's attire to kinky or fetish-themed clothing. Ensure the materials, such as latex or leather, and the design are integrated naturally onto the subject. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Prioritize the kinky dress edit while maintaining visual coherence in unedited areas. Dress in kinky clothes. Change outfit to a fetish style. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be the subject in kinky attire."""

INSTRUCT_PROMPT_EDIT_OP_DRESS_UNDRESS = """Keep pose. Keep angle. Keep viewing direction. Modify the subject's attire to be partially removed or in a state of undress. Ensure the transition between clothing and skin is realistic and fits the pose naturally. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Prioritize the undressing edit while keeping the rest of the scene intact. Undress the subject. Remove some clothing. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be the subject in a state of undress."""

INSTRUCT_PROMPT_EDIT_OP_DRESS_NUDE = """Keep pose. Keep angle. Keep viewing direction. Modify the subject to be completely nude. Remove all clothing and reconstruct the underlying anatomy realistically and accurately. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure the nudity is integrated naturally into the pose and composition. Make the subject nude. Remove all clothes. Prioritize the nude edit while keeping the background and unedited areas in focus. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be the subject completely nude."""
INSTRUCT_PROMPT_EDIT_OP_CHANGE_COMPOSITION = """Keep the original visual style. Keep the original aesthetic. Change the composition, layout, or position of the targeted elements. Move or reposition subjects as requested while strictly maintaining their original appearance, textures, and lighting. Ensure the repositioning is integrated naturally into the scene. Change the composition. Reposition the target. Prioritize the request to alter the layout while keeping the visual style and unedited areas intact. Ensure that lighting remains consistent with the original scene. Ensure shadows are updated correctly for the new positions. Keep in focus. The result should be an accurate repositioned version maintaining the original style."""
