INSTRUCT_PROMPT_STYLE_PHOTOREALISM = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to show real details. Make the it look like a professional photograph. Keep subject position and their pose the same as the reference. Ensure face looks real. Make sure anatomy is accurately represented. Normal anatomy. Make face look real. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure lighting is accurate. Ensure shadows are displayed correctly. Keep in focus. Sharply focused photograph."""

INSTRUCT_PROMPT_STYLE_3D = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a high-quality 3D render. Make it look like CGI graphics. Keep subject position and their pose the same as the reference. Ensure materials look physically based. Make sure anatomy is accurately represented within the style. Make surface details look rendered. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure volumetric lighting is accurate. Ensure ambient occlusion and shadows are displayed correctly. Keep in focus. High definition 3D render."""

INSTRUCT_PROMPT_STYLE_ANIME = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like an official anime illustration. Make it look like 2D animation key art. Keep subject position and their pose the same as the reference. Ensure face follows anime aesthetics. Make sure anatomy follows anime style conventions. Make coloring look like cel shading. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure lighting fits the anime style. Ensure clean lines and flat colors. Keep in focus. High quality anime drawing."""

INSTRUCT_PROMPT_STYLE_DIGITAL_DRAWING = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a clean digital drawing. Make it look like crisp line art. Keep subject position and their pose the same as the reference. Ensure lines are smooth and defined. Make sure anatomy is stylized but recognizable. Make shading look digital. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure lighting highlights the form. Ensure contrast is maintained. Keep in focus. Clean digital illustration."""

INSTRUCT_PROMPT_STYLE_DIGITAL_PAINTING = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a digital painting. Make it look like painterly art. Keep subject position and their pose the same as the reference. Ensure brushstrokes are visible and artistic. Make sure anatomy is artistically rendered. Make colors blend naturally. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure painterly lighting. Ensure soft shadows and rich textures. Keep in focus. Detailed digital painting."""

INSTRUCT_PROMPT_STYLE_FANTASY = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like fantasy art. Make it look like an epic illustration. Keep subject position and their pose the same as the reference. Ensure mystical elements are integrated. Make sure anatomy fits the fantasy theme. Make details look ornate and magical. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure dramatic and atmospheric lighting. Ensure rich, deep colors. Keep in focus. Epic fantasy artwork."""

INSTRUCT_PROMPT_STYLE_COMIC_BOOK = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a comic book illustration. Make it look like graphic novel art. Keep subject position and their pose the same as the reference. Ensure bold ink lines and dynamic shading. Make sure anatomy is expressive. Make coloring look like comic book printing. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure high contrast lighting. Ensure halftones or flat colors are used. Keep in focus. Western comic book style."""
