INSTRUCT_PROMPT_STYLE_PHOTOREALISM = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to show real details. Make the it look like a professional photograph. Keep subject position and their pose the same as the reference. Ensure face looks real. Make sure anatomy is accurately represented. Normal anatomy. Make face look real. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure lighting is accurate. Ensure shadows are displayed correctly. Keep in focus. Sharply focused photograph."""

INSTRUCT_PROMPT_STYLE_3D = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a high-quality 3D render. Make it look like CGI graphics. Keep subject position and their pose the same as the reference. Ensure materials look physically based. Make sure anatomy is accurately represented within the style. Make surface details look rendered. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure volumetric lighting is accurate. Ensure ambient occlusion and shadows are displayed correctly. Keep in focus. High definition 3D render."""

INSTRUCT_PROMPT_STYLE_ANIME = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like an official anime illustration. Make it look like 2D animation key art. Keep subject position and their pose the same as the reference. Ensure face follows anime aesthetics. Make sure anatomy follows anime style conventions. Make coloring look like cel shading. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure lighting fits the anime style. Ensure clean lines and flat colors. Keep in focus. High quality anime drawing."""

INSTRUCT_PROMPT_STYLE_DIGITAL_DRAWING = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a clean digital drawing. Make it look like crisp line art. Keep subject position and their pose the same as the reference. Ensure lines are smooth and defined. Make sure anatomy is stylized but recognizable. Make shading look digital. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure lighting highlights the form. Ensure contrast is maintained. Keep in focus. Clean digital illustration."""

INSTRUCT_PROMPT_STYLE_DIGITAL_PAINTING = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a digital painting. Make it look like painterly art. Keep subject position and their pose the same as the reference. Ensure brushstrokes are visible and artistic. Make sure anatomy is artistically rendered. Make colors blend naturally. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure painterly lighting. Ensure soft shadows and rich textures. Keep in focus. Detailed digital painting."""

INSTRUCT_PROMPT_STYLE_FANTASY = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like fantasy art. Make it look like an epic illustration. Keep subject position and their pose the same as the reference. Ensure mystical elements are integrated. Make sure anatomy fits the fantasy theme. Make details look ornate and magical. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure dramatic and atmospheric lighting. Ensure rich, deep colors. Keep in focus. Epic fantasy artwork."""

INSTRUCT_PROMPT_STYLE_COMIC_BOOK = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a comic book illustration. Make it look like graphic novel art. Keep subject position and their pose the same as the reference. Ensure bold ink lines and dynamic shading. Make sure anatomy is expressive. Make coloring look like comic book printing. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure high contrast lighting. Ensure halftones or flat colors are used. Keep in focus. Western comic book style."""

INSTRUCT_PROMPT_STYLE_DISNEY = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a classical 2D animated character. Make it look like a hand-drawn animation cel. Keep subject position and their pose the same as the reference. Ensure facial features follow classical Disney aesthetics with clean ink lines. Make sure anatomy is accurately represented within the traditional animation proportions. Make coloring look like flat ink-and-paint with soft painted highlights. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure soft, painted lighting fits the 2D style. Ensure smooth line art and soft backgrounds. Keep in focus. Classical 2D animation style."""

INSTRUCT_PROMPT_STYLE_PIXAR = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a 3D animated character. Make it look like a modern Pixar-style animated feature film. Keep subject position and their pose the same as the reference. Ensure facial features follow modern 3D aesthetics with large expressive eyes. Make sure anatomy is accurately represented within the high-end CGI proportions. Make skin and surfaces look like soft subsurface scattering with PBR textures. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure cinematic volumetric lighting fits the 3D animation style. Ensure soft ray-traced shadows and detailed highlights are displayed correctly. Keep in focus. High-quality 3D animation style."""

INSTRUCT_PROMPT_STYLE_GRITTY_COMIC = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a gritty comic book character. Make it look like noir graphic novel art. Keep subject position and their pose the same as the reference. Ensure heavy ink washes and cross-hatching follow gritty aesthetics. Make sure anatomy is accurately represented within a rugged, expressive style. Make textures look weathered and dirty. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure high-contrast chiaroscuro lighting fits the noir style. Ensure deep black shadows are displayed correctly. Keep in focus. Dark and gritty comic style."""

INSTRUCT_PROMPT_STYLE_LEWD_ANIME = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like an explicit anime illustration. Make it look like high-quality erotic art. Keep subject position and their pose the same as the reference. Ensure face follows lewd anime aesthetics with blush and moisture. Make sure anatomy is emphasized and accurately represented within the genre's style. Make skin look soft with detailed highlights and shading. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure atmospheric lighting fits the mood. Ensure detailed shading and textures. Keep in focus. High quality erotic anime style."""

INSTRUCT_PROMPT_STYLE_CYBERPUNK = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like cyberpunk art. Make it look like a high-tech futuristic scene. Keep subject position and their pose the same as the reference. Ensure glowing neon elements and cybernetic details follow cyberpunk aesthetics. Make sure anatomy is accurately represented with metallic panels. Make surfaces look rain-slicked and reflective. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure dramatic neon lighting fits the style. Ensure high contrast and vibrant glow. Keep in focus. Cyberpunk aesthetic."""

INSTRUCT_PROMPT_STYLE_GHIBLI = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a Ghibli illustration. Make it look like a hand-painted animation background. Keep subject position and their pose the same as the reference. Ensure watercolor textures and soft edges follow Ghibli aesthetics. Make sure anatomy is stylized but natural. Make greenery and clouds look painterly. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure soft pastoral lighting fits the scene. Ensure warm, natural colors. Keep in focus. Studio Ghibli art style."""

INSTRUCT_PROMPT_STYLE_SYNTHWAVE = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like synthwave art. Make it look like a retro-futuristic digital scene. Keep subject position and their pose the same as the reference. Ensure digital grids and chrome reflections follow synthwave aesthetics. Make sure anatomy is stylized with vibrant outlines. Make background look like a sunset grid. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure vibrant purple and pink lighting fits the style. Ensure scanline effects and high contrast. Keep in focus. 1980s synthwave style."""

INSTRUCT_PROMPT_STYLE_GROENING = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a Matt Groening character. Make it look like an animation cel from The Simpsons or Futurama. Keep subject position and their pose the same as the reference. Ensure large bug eyes and iconic overbite follow Groening aesthetics. Make sure anatomy is simplified with thick, clean black outlines. Make skin tone yellow where appropriate. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure flat, bright lighting fits the cartoon style. Ensure simple shading. Keep in focus. Matt Groening animation style."""

INSTRUCT_PROMPT_STYLE_MACFARLANE = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a Seth MacFarlane character. Make it look like an animation cel from Family Guy or American Dad. Keep subject position and their pose the same as the reference. Ensure circular eye designs and distinct facial features follow MacFarlane aesthetics. Make sure anatomy is simplified with clean digital lines. Make coloring flat and consistent. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure standard sitcom animation lighting fits the style. Ensure minimal shading. Keep in focus. Seth MacFarlane animation style."""

INSTRUCT_PROMPT_STYLE_SOUTH_PARK = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a South Park character. Make it look like a construction paper cutout. Keep subject position and their pose the same as the reference. Ensure simple geometric shapes and paper textures follow the South Park aesthetic. Make sure anatomy is simplified into cut-out segments. Make the mouth and eyes look like paper overlays. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure flat lighting fits the cutout style. Ensure the appearance of construction paper grain. Keep in focus. South Park animation style."""
