INSTRUCT_PROMPT_STYLE_PHOTOREALISM = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to show real details. Make the it look like a professional photograph. Keep subject position and their pose the same as the reference. Ensure image looks real. Make sure anatomy is accurately represented. Normal anatomy. Make face look real. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure that lighting is accurate for the scene. Ensure shadows are displayed correctly. Keep in focus. The result should be a sharply focused photograph."""

INSTRUCT_PROMPT_STYLE_3D = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like a high-quality 3D render. Make it look like CGI graphics. Keep subject position and their pose the same as the reference. Ensure materials look physically based. Make sure anatomy is accurately represented within the style. Make surface details look rendered. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure volumetric lighting is accurate. Ensure ambient occlusion and shadows are displayed correctly. Keep in focus. The result should be a high definition 3D render."""

INSTRUCT_PROMPT_STYLE_ANIME = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like an official anime illustration. Make it look like 2D animation key art. Keep subject position and their pose the same as the reference. Ensure image follows anime aesthetics. Make sure anatomy follows anime style conventions. Make coloring look like cel shading. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure lighting fits the anime style. Ensure clean lines and flat colors. Keep in focus. The result should be a high quality anime drawing."""

INSTRUCT_PROMPT_STYLE_DIGITAL_DRAWING = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like a clean digital drawing. Make it look like crisp line art. Keep subject position and their pose the same as the reference. Ensure lines are smooth and defined. Make sure anatomy is stylized but recognizable. Make shading look digital. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure lighting highlights the form. Ensure contrast is maintained. Keep in focus. The result should be a clean digital illustration."""

INSTRUCT_PROMPT_STYLE_DIGITAL_PAINTING = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like a digital painting. Make it look like painterly art. Keep subject position and their pose the same as the reference. Ensure brushstrokes are visible and artistic. Make sure anatomy is artistically rendered. Make colors blend naturally. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure painterly lighting. Ensure soft shadows and rich textures. Keep in focus. The result should be a detailed digital painting."""

INSTRUCT_PROMPT_STYLE_FANTASY = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like fantasy art. Make it look like an epic illustration. Keep subject position and their pose the same as the reference. Ensure mystical elements are integrated. Make sure anatomy fits the fantasy theme. Make details look ornate and magical. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure dramatic and atmospheric lighting. Ensure rich, deep colors. Keep in focus. The result should be epic fantasy artwork."""

INSTRUCT_PROMPT_STYLE_COMIC_BOOK = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like a comic book illustration. Make it look like graphic novel art. Keep subject position and their pose the same as the reference. Ensure bold ink lines and dynamic shading. Make sure anatomy is expressive. Make coloring look like comic book printing. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure high contrast lighting. Ensure flat colors are used. Keep in focus. The result should be in a western comic book style."""

INSTRUCT_PROMPT_STYLE_DISNEY = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the classic 2D animation style of the Disney franchise, featuring clean ink lines and soft painted backgrounds. Make it look like a hand-drawn Disney animation cel. Keep subject position and their pose the same as the reference. Ensure facial features follow the classic 2D animation style of the Disney franchise with clean ink lines. Make sure anatomy is accurately represented within the Disney proportions. Make coloring look like flat ink-and-paint with soft painted highlights. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure soft, painted lighting fits the 2D style. Ensure smooth line art and soft backgrounds. Keep in focus. The result should be in the classic 2D animation style of the Disney franchise."""

INSTRUCT_PROMPT_STYLE_PIXAR = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the modern 3D animation style of the Pixar franchise, featuring soft subsurface scattering and cinematic lighting. Make it look like a Pixar 3D animated feature film. Keep subject position and their pose the same as the reference. Ensure facial features follow the modern 3D animation style of the Pixar franchise with large expressive eyes. Make sure anatomy is accurately represented within the Pixar proportions. Make skin and surfaces look like soft subsurface scattering with PBR textures. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure cinematic volumetric lighting fits the 3D animation style. Ensure soft ray-traced shadows and detailed highlights are displayed correctly. Keep in focus. The result should be in the modern 3D animation style of the Pixar franchise."""

INSTRUCT_PROMPT_STYLE_GRITTY_COMIC = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like a gritty comic book character. Make it look like noir graphic novel art. Keep subject position and their pose the same as the reference. Ensure heavy ink washes and cross-hatching follow gritty aesthetics. Make sure anatomy is accurately represented within a rugged, expressive style. Make textures look weathered and dirty. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure high-contrast chiaroscuro lighting fits the noir style. Ensure deep black shadows are displayed correctly. Keep in focus. The result should be in a dark and gritty comic style."""

INSTRUCT_PROMPT_STYLE_LEWD_ANIME = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like an explicit anime illustration. Make it look like high-quality erotic art. Keep subject position and their pose the same as the reference. Ensure image follows lewd anime aesthetics with blush and moisture. Make sure anatomy is emphasized and accurately represented within the genre's style. Make skin look soft with detailed highlights and shading. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure atmospheric lighting fits the mood. Ensure detailed shading and textures. Keep in focus. The result should be in a high quality erotic anime style."""

INSTRUCT_PROMPT_STYLE_CYBERPUNK = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like cyberpunk art. Make it look like a high-tech futuristic scene. Keep subject position and their pose the same as the reference. Ensure glowing neon elements and cybernetic details follow cyberpunk aesthetics. Make sure anatomy is accurately represented with metallic panels. Make surfaces look rain-slicked and reflective. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure dramatic neon lighting fits the style. Ensure high contrast and vibrant glow. Keep in focus. The result should have a cyberpunk aesthetic."""

INSTRUCT_PROMPT_STYLE_GHIBLI = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the hand-painted watercolor style of the Studio Ghibli franchise, featuring soft edges and a painterly, pastoral aesthetic. Make it look like a hand-painted Studio Ghibli animation background. Keep subject position and their pose the same as the reference. Ensure watercolor textures and soft edges follow the hand-painted watercolor style of the Studio Ghibli franchise. Make sure anatomy is stylized but natural. Make greenery and clouds look painterly. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure soft pastoral lighting fits the style. Ensure warm, natural colors. Keep in focus. The result should be in the hand-painted watercolor style of the Studio Ghibli franchise."""

INSTRUCT_PROMPT_STYLE_SYNTHWAVE = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like synthwave art. Make it look like a retro-futuristic digital scene. Keep subject position and their pose the same as the reference. Ensure digital grids and chrome reflections follow synthwave aesthetics. Make sure anatomy is stylized with vibrant outlines. Make background look like a sunset grid. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure vibrant purple and pink lighting fits the style. Ensure scanline effects and high contrast. Keep in focus. The result should be in a 1980s synthwave style."""

INSTRUCT_PROMPT_STYLE_GROENING = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the satirical cartoon style of the Matt Groening franchise, featuring clean, bold lines and flat coloring. Make it look like an animation cel from the Matt Groening franchise. Keep subject position and their pose the same as the reference. Ensure large bug eyes and iconic overbite follow the satirical cartoon style. Make sure anatomy is simplified with thick, clean black outlines. Make skin tone yellow where appropriate. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure flat, bright lighting fits the style. Ensure simple shading. Keep in focus. The result should be in the satirical cartoon style of the Matt Groening franchise."""

INSTRUCT_PROMPT_STYLE_MACFARLANE = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the modern sitcom animation style of the Seth MacFarlane franchise, featuring clean digital line work and flat colors. Make it look like an animation cel from the Seth MacFarlane franchise. Keep subject position and their pose the same as the reference. Ensure circular eye designs and distinct facial features follow the modern animated sitcom style. Make sure anatomy is simplified with clean digital lines. Make coloring flat and consistent. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure standard sitcom animation lighting fits the style. Ensure minimal shading. Keep in focus. The result should be in the modern sitcom animation style of the Seth MacFarlane franchise."""

INSTRUCT_PROMPT_STYLE_SOUTH_PARK = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the construction paper cutout style of the South Park franchise, featuring simple geometric subjects and paper textures. Make it look like a construction paper cutout from the South Park franchise. Keep subject position and their pose the same as the reference. Ensure simple geometric shapes and paper textures follow the construction paper cutout style. Make sure anatomy is simplified into cut-out segments. Make the mouth and eyes look like paper overlays. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure flat lighting fits the cutout style. Ensure the appearance of construction paper grain. Keep in focus. The result should be in the construction paper cutout style of the South Park franchise."""

INSTRUCT_PROMPT_STYLE_MARIO = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the 3D video game style of the Super Mario franchise, featuring smooth surfaces and rounded geometry. Make it look like a 3D Super Mario video game asset. Keep subject position and their pose the same as the reference. Ensure rounded shapes and primary colors follow the 3D video game style of the Super Mario franchise. Make sure anatomy is cartoonish and friendly. Make textures look smooth and plastic-like. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure bright, cheerful lighting fits the game style. Ensure soft shadows. Keep in focus. The result should be in the 3D video game style of the Super Mario franchise."""

INSTRUCT_PROMPT_STYLE_MINECRAFT = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the voxel-based video game style of the Minecraft franchise, featuring blocky anatomy and low-res pixel textures. Make it look like a Minecraft voxel model. Keep subject position and their pose the same as the reference. Ensure everything is composed of cubes following the voxel-based style of the Minecraft franchise. Make sure anatomy is blocky and pixelated. Make surfaces look like low-res pixel textures. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure blocky lighting fits the voxel style. Ensure no curves, only straight edges. Keep in focus. The result should be in the voxel-based video game style of the Minecraft franchise."""

INSTRUCT_PROMPT_STYLE_POKEMON = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the anime style of the Pokemon franchise, featuring distinct creature designs and cel-shaded coloring. Make it look like official Pokemon artwork. Keep subject position and their pose the same as the reference. Ensure clean outlines and vibrant colors follow the anime style of the Pokemon franchise. Make sure anatomy fits the Pokemon design language. Make shading look cel-shaded. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure anime-style lighting fits the series. Ensure distinctive eyes and features. Keep in focus. The result should be in the anime style of the Pokemon franchise."""

INSTRUCT_PROMPT_STYLE_RETRO_GAME = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like a retro video game sprite. Make it look like 16-bit pixel art. Keep subject position and their pose the same as the reference. Ensure visible pixels and limited palette follow retro gaming aesthetics. Make sure anatomy is simplified for low resolution. Make shading use dithering techniques. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure dithered lighting fits the sprite style. Ensure jagged edges. Keep in focus. The result should be in a retro video game style."""

INSTRUCT_PROMPT_STYLE_RPG = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like an RPG video game character. Make it look like a fantasy game asset. Keep subject position and their pose the same as the reference. Ensure detailed armor and accessories follow RPG aesthetics. Make sure anatomy fits the heroic fantasy class style. Make textures look detailed and worn. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure atmospheric lighting fits the game style. Ensure isometric perspective hints if applicable. Keep in focus. The result should be in an RPG fantasy style."""

INSTRUCT_PROMPT_STYLE_ZELDA_RETRO = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the 16-bit video game style of the Legend of Zelda franchise, featuring vibrant pixel art and distinct outlines. Make it look like a 16-bit Legend of Zelda adventure game sprite. Keep subject position and their pose the same as the reference. Ensure top-down perspective and pixel art follow the 16-bit video game style of the Legend of Zelda franchise. Make sure anatomy is simplified. Make colors vibrant and fantasy-themed. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure bright fantasy lighting fits the style. Ensure distinct outlines. Keep in focus. The result should be in the 16-bit video game style of the Legend of Zelda franchise."""

INSTRUCT_PROMPT_STYLE_ZELDA_3D = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the cel-shaded 3D video game style of the Legend of Zelda franchise, featuring soft atmospheric lighting and cel-shaded rendering. Make it look like cel-shaded 3D graphics from the Legend of Zelda franchise. Keep subject position and their pose the same as the reference. Ensure cel-shaded 3D rendering follows the cel-shaded 3D video game style of the Legend of Zelda franchise. Make sure anatomy fits the stylized Hylian proportions. Make textures look painterly and soft. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure soft, atmospheric lighting fits the style. Ensure gentle rim lighting. Keep in focus. The result should be in the cel-shaded 3D video game style of the Legend of Zelda franchise."""

INSTRUCT_PROMPT_STYLE_PIXEL_ART = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like pixel art. Make it look like a low-resolution digital drawing. Keep subject position and their pose the same as the reference. Ensure jagged edges and visible pixels follow pixel art aesthetics. Make sure anatomy is defined by pixel clusters. Make shading use limited colors. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure digital lighting fits the medium. Ensure clear grid alignment. Keep in focus. The result should be in a pixel art style."""

INSTRUCT_PROMPT_STYLE_ANALOG_FILM = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like it was shot on analog film. Make it look like a vintage photograph. Keep subject position and their pose the same as the reference. Ensure film grain and color shifts follow analog photography aesthetics. Make sure anatomy looks natural and candid. Make textures look organic and slightly soft. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure natural lighting fits the film style. Ensure minor light leaks. Keep in focus. The result should be in an analog film style."""

INSTRUCT_PROMPT_STYLE_FAIRY_TALE = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like a fairy tale illustration. Make it look like storybook art. Keep subject position and their pose the same as the reference. Ensure whimsical details and soft lines follow fairy tale aesthetics. Make sure anatomy fits the storybook style. Make colors soft and magical. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure dreamy lighting fits the enchanted theme. Ensure illustrative quality. Keep in focus. The result should be in a fairy tale style."""

INSTRUCT_PROMPT_STYLE_GOTHIC = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like gothic art. Make it look like a dark, ornate masterpiece. Keep subject position and their pose the same as the reference. Ensure sharp angles and dramatic details follow gothic aesthetics. Make sure anatomy is elegant and skin tone is pale. Make clothing and background look intricate and brooding. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure moody, low-key lighting fits the gothic style. Ensure deep shadows. Keep in focus. The result should be in a gothic art style."""

INSTRUCT_PROMPT_STYLE_LOVECRAFTIAN = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like Lovecraftian horror. Make it look like an eldritch nightmare. Keep subject position and their pose the same as the reference. Ensure tentacles and non-Euclidean geometry follow cosmic horror aesthetics. Make sure anatomy is twisted and unnatural. Make textures look slimy and ancient. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure dark, oppressive lighting fits the horror style. Ensure fear-inducing atmosphere. Keep in focus. The result should be in a Lovecraftian style."""

INSTRUCT_PROMPT_STYLE_STAINED_GLASS = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like a stained glass window. Make it look like glass art. Keep subject position and their pose the same as the reference. Ensure thick black lead lines and vibrant glass panes follow stained glass aesthetics. Make sure anatomy is stylized and fragmented. Make colors translucent and glowing. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure backlighting fits the glass style. Ensure geometric segmentation. Keep in focus. The result should be in a stained glass style."""

INSTRUCT_PROMPT_STYLE_FILM_NOIR = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like a film noir scene. Make it look like a black and white crime movie. Keep subject position and their pose the same as the reference. Ensure high contrast and dramatic shadows follow noir aesthetics. Make sure anatomy fits the dramatic, moody style. Make everything black and white. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure hard lighting and deep blacks fit the genre. Ensure cinematic composition. Keep in focus. The result should be in a film noir style."""

INSTRUCT_PROMPT_STYLE_CLAYMATION = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like a claymation figure. Make it look like stop-motion animation. Keep subject position and their pose the same as the reference. Ensure plasticine textures and visible fingerprints follow claymation aesthetics. Make sure anatomy is chunky and molded. Make clothing look like real life fabric and any body parts look like clay. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure studio lighting fits the miniature style. Ensure lack of motion blur. Keep in focus. The result should be in a claymation style."""

INSTRUCT_PROMPT_STYLE_ORIGAMI = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like origami. Make it look like folded paper art. Keep subject position and their pose the same as the reference. Ensure sharp creases and geometric folds follow origami aesthetics. Make sure anatomy is abstract and angular. Make textures look like paper. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure soft studio lighting fits the papercraft style. Ensure no curves, only folds. Keep in focus. The result should be in an origami style."""

INSTRUCT_PROMPT_STYLE_NEONPUNK = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like neonpunk art. Make it look like a blacklight poster. Keep subject position and their pose the same as the reference. Ensure fluorescent colors and glowing lines follow neonpunk aesthetics. Make sure anatomy is highlighted by UV light. Make textures glow. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure UV and neon lighting fits the style. Ensure high contrast against black. Keep in focus. The result should be in a neonpunk style."""

INSTRUCT_PROMPT_STYLE_GRAFFITI = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like a graffiti mural. Make it look like spray paint on a wall. Keep subject position and their pose the same as the reference. Ensure spray paint textures and drips follow graffiti aesthetics. Make sure anatomy is stylized and bold. Make the background look like an urban wall. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure outdoor lighting fits the street art style. Ensure vibrant colors. Keep in focus. The result should be in a graffiti style."""

INSTRUCT_PROMPT_STYLE_LOONEY_TUNES = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the classic cartoon style of the Looney Tunes franchise, featuring elastic anatomy and dynamic ink lines. Make it look like a classic Looney Tunes cartoon. Keep subject position and their pose the same as the reference. Ensure exaggerated features and elastic anatomy follow the classic cartoon style of the Looney Tunes franchise. Make sure anatomy is rubbery and expressive. Make colors flat and bright. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure flat cartoon lighting fits the style. Ensure dynamic outlines. Keep in focus. The result should be in the classic cartoon style of the Looney Tunes franchise."""

INSTRUCT_PROMPT_STYLE_NICKELODEON = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the 90s cartoon style of the Nickelodeon franchise, featuring vibrant colors and distinct shapes. Make it look like a 90s Nickelodeon cartoon. Keep subject position and their pose the same as the reference. Ensure quirky shapes and bold lines follow the 90s cartoon style of the Nickelodeon franchise. Make sure anatomy is stylized and slightly wacky. Make colors vibrant and saturated. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure flat animation lighting fits the style. Ensure thick ink lines. Keep in focus. The result should be in the 90s cartoon style of the Nickelodeon franchise."""

INSTRUCT_PROMPT_STYLE_CARTOON_NETWORK = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the geometric cartoon style of the Cartoon Network franchise, featuring sharp angles and thick outlines. Make it look like a Cartoon Network show. Keep subject position and their pose the same as the reference. Ensure geometric shapes and thick outlines follow the geometric cartoon style of the Cartoon Network franchise. Make sure anatomy is sharp and angular. Make colors flat and bold. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure flat animation lighting fits the style. Ensure distinct silhouettes. Keep in focus. The result should be in the geometric cartoon style of the Cartoon Network franchise."""

INSTRUCT_PROMPT_STYLE_ADULT_SWIM = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the alternative animation style of the Adult Swim franchise, featuring limited animation techniques and distinct visual styles. Make it look like an Adult Swim show. Keep subject position and their pose the same as the reference. Ensure crude alternative styles follow the alternative animation style of the Adult Swim franchise. Make sure anatomy fits the specific show style. Make textures look as if make using simplified animation. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure flat lighting fits the style. Ensure unique character designs. Keep in focus. The result should be in the alternative animation style of the Adult Swim franchise."""

INSTRUCT_PROMPT_STYLE_ADVENTURE_TIME = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the whimsical cartoon style of the Adventure Time franchise, featuring pastel colors and thin, consistent line work. Make it look like a character from the Adventure Time franchise. Keep subject position and their pose the same as the reference. Ensure noodly limbs and dot eyes (if applicable) follow the whimsical cartoon style of the Adventure Time franchise. Make sure anatomy is rubbery and simplified. Make colors pastel and happy. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure flat, bright lighting fits the style. Ensure thin, consistent outlines. Keep in focus. The result should be in the whimsical cartoon style of the Adventure Time franchise."""

INSTRUCT_PROMPT_STYLE_DRAGON_BALL_Z = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the shonen anime style of the Dragon Ball Z franchise, featuring intense expressions and dramatic shading. Make it look like a Dragon Ball Z anime. Keep subject position and their pose the same as the reference. Ensure muscular builds and angular eyes follow the shonen anime style of the Dragon Ball Z franchise. Make sure anatomy is hyper-defined and strong. Make hair spiky and voluminous. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure dramatic anime lighting fits the style. Ensure hard shadows. Keep in focus. The result should be in the shonen anime style of the Dragon Ball Z franchise."""

INSTRUCT_PROMPT_STYLE_COWBOY_BEBOP = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the noir anime style of the Cowboy Bebop franchise, featuring high-contrast lighting and detailed mechanical designs. Make it look like a Cowboy Bebop anime. Keep subject position and their pose the same as the reference. Ensure realistic proportions and stylish designs follow the noir anime style of the Cowboy Bebop franchise. Make sure anatomy is tall and lean. Make clothing look detailed and worn. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure cinematic, moody lighting fits the style. Ensure high-quality cel shading. Keep in focus. The result should be in the noir anime style of the Cowboy Bebop franchise."""

INSTRUCT_PROMPT_STYLE_RICK_AND_MORTY = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the sci-fi cartoon style of the Rick and Morty franchise, featuring flat colors and specific facial features. Make it look like a character from the Rick and Morty franchise. Keep subject position and their pose the same as the reference. Ensure specific pupil scribbles and droopy mouths follow the sci-fi cartoon style of the Rick and Morty franchise. Make sure anatomy is simplified and rounded. Make colors flat and consistent. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure flat lighting fits the style. Ensure standard line weights. Keep in focus. The result should be in the sci-fi cartoon style of the Rick and Morty franchise."""

INSTRUCT_PROMPT_STYLE_BOBS_BURGERS = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the animated sitcom style of the Bob's Burgers franchise, featuring flat shading and distinct body shapes. Make it look like a character from the Bob's Burgers franchise. Keep subject position and their pose the same as the reference. Ensure thick outlines and lack of chins follow the animated sitcom style of the Bob's Burgers franchise. Make sure anatomy is somewhat tubular and awkward. Make colors earth-toned and flat. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure flat lighting fits the style. Ensure consistent character models. Keep in focus. The result should be in the animated sitcom style of the Bob's Burgers franchise."""

INSTRUCT_PROMPT_STYLE_GRAVITY_FALLS = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the mystery cartoon style of the Gravity Falls franchise, featuring smooth line art and specific eye shapes. Make it look like a character from the Gravity Falls franchise. Keep subject position and their pose the same as the reference. Ensure specific eye shapes and rounded features follow the mystery cartoon style of the Gravity Falls franchise. Make sure anatomy is appealing and consistent. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure atmospheric lighting fits the style. Ensure smooth line art. Keep in focus. The result should be in the mystery cartoon style of the Gravity Falls franchise."""

INSTRUCT_PROMPT_STYLE_SAILOR_MOON = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the magical girl anime style of the Sailor Moon franchise, featuring soft romantic lighting and pastel colors. Make it look like a character from the Sailor Moon franchise. Keep subject position and their pose the same as the reference. Ensure large sparkling eyes and long legs follow the magical girl anime style of the Sailor Moon franchise. Make sure anatomy is slender and elegant. Make hair flowing and detailed. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure a soft, romantic lighting that fits the style. Ensure pastel colors. Keep in focus. The result should be in the magical girl anime style of the Sailor Moon franchise."""

INSTRUCT_PROMPT_STYLE_CCTV_EDIT = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to look like it was recorded on a CCTV security camera. Make it look like surveillance footage. Keep subject position and their pose the same as the reference. Ensure the aesthetic follows security camera characteristics. Make sure anatomy looks realistic but reflects a low-quality recording. Make textures look grainy and somewhat degraded. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure harsh artificial lighting fits the surveillance style. Ensure a high-contrast monitoring perspective. Keep in focus. The result should be in a CCTV security camera style."""

INSTRUCT_PROMPT_STYLE_CCTV_RAW = """Generate subjects and environment to look like they were recorded on a CCTV security camera. Make it look like surveillance footage. Ensure the aesthetic follows security camera characteristics. Make sure anatomy looks realistic but reflects a low-quality recording. Make textures look grainy and somewhat degraded. Ensure harsh artificial lighting fits the surveillance style. Ensure a high-contrast monitoring perspective. Keep in focus. The result should be in a CCTV security camera style."""

INSTRUCT_PROMPT_STYLE_POLAROID = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a Polaroid instant film photograph. Make it look like a vintage instant camera capture. Keep subject position and their pose the same as the reference. Ensure face has warm, slightly faded tones characteristic of Polaroid film. Make sure anatomy appears soft and slightly out of focus with natural imperfections. Make colors look desaturated with a warm color cast. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure soft, natural lighting with minimal shadows. Ensure faded edges and vignetting are visible. Keep in focus. Vintage Polaroid instant film aesthetic."""

INSTRUCT_PROMPT_STYLE_GLITCH_ART = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like glitch art. Make it look like intentional digital corruption and pixel displacement. Keep subject position and their pose the same as the reference. Ensure face has color channel separation and digital artifacts. Make sure anatomy shows displaced pixels and data corruption effects. Make textures look fragmented with visible digital errors. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure RGB channel misalignment is visible. Ensure scanlines and pixelation artifacts are prominently displayed. Keep in focus. High-quality glitch art aesthetic."""

INSTRUCT_PROMPT_STYLE_PIXEL_ART = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like pixel art. Make it look like retro arcade or 16-bit game graphics. Keep subject position and their pose the same as the reference. Ensure face has limited color palette with solid pixel blocks. Make sure anatomy is blocky and stylized with clear pixel edges. Make coloring look like indexed color mode with distinct hues. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure pixelated shading and dithering patterns are accurate. Ensure visible individual pixels define all forms. Keep in focus. High-quality pixel art aesthetic."""

INSTRUCT_PROMPT_STYLE_WATERCOLOR = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a watercolor painting. Make it look like wet paint on paper with organic color bleeding. Keep subject position and their pose the same as the reference. Ensure face has soft, translucent color washes with natural color diffusion. Make sure anatomy appears fluid and organic with visible paper texture. Make colors blend and bleed naturally into each other. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure soft edges and transparent layers are characteristic. Ensure paper texture and watermark patterns are visible. Keep in focus. Detailed watercolor painting aesthetic."""

INSTRUCT_PROMPT_STYLE_KODACHROME = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like Kodachrome film photography. Make it look like 1950s-70s color slide film with distinctive color rendering. Keep subject position and their pose the same as the reference. Ensure face has rich, saturated Kodachrome color tones. Make sure anatomy displays the warm, distinctive color palette of Kodachrome stock. Make colors look vibrant with slightly exaggerated saturation characteristic of the film. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure warm, golden lighting with rich highlights. Ensure deep, saturated shadows are displayed correctly. Keep in focus. Classic Kodachrome color film aesthetic."""

INSTRUCT_PROMPT_STYLE_GRAPHIC_NOVEL = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a graphic novel illustration. Make it look like professional comic book panel art. Keep subject position and their pose the same as the reference. Ensure face follows graphic novel aesthetics with bold, expressive line work. Make sure anatomy is dramatically stylized with dynamic poses and exaggerated proportions. Make coloring look like professional comic book printing with limited but vibrant color ranges. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure dramatic, cinematic lighting that enhances mood and storytelling. Ensure bold ink lines and dynamic shadows are prominently featured. Keep in focus. High-quality graphic novel aesthetic."""

INSTRUCT_PROMPT_STYLE_CEL_SHADED = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like cel-shaded video game art. Make it look like hand-drawn illustration rendered in 3D. Keep subject position and their pose the same as the reference. Ensure face has thick black outlines and flat color blocks. Make sure anatomy is stylized with bold edge definition. Make shading look like simplified color areas rather than gradients. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure solid colors with clear boundaries define all forms. Ensure thick black ink lines outline all edges prominently. Keep in focus. High-quality cel-shaded video game aesthetic."""

INSTRUCT_PROMPT_STYLE_VIDEO_GAME = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a generic video game character. Make it look like standard 3D video game graphics. Keep subject position and their pose the same as the reference. Ensure face has game engine rendering with realistic proportions. Make sure anatomy shows typical game character modeling with clean geometry. Make textures look like video game materials with moderate detail. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure video game lighting with clear light sources. Ensure game engine rendering quality with balanced shaders. Keep in focus. High-quality video game aesthetic."""

INSTRUCT_PROMPT_STYLE_SKYRIM = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like it belongs in Skyrim from The Elder Scrolls. Make it look like fantasy medieval RPG game graphics. Keep subject position and their pose the same as the reference. Ensure the subject displays Skyrim aesthetic with fantasy game proportions and style. Make sure textures show medieval fantasy game materials with a clean but aged appearance. Make colors look like natural fantasy game color grading with warm tones. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure warm, natural fantasy lighting fitting the medieval Nordic setting. Ensure detailed game textures with a polished but classic game quality are displayed throughout. Keep in focus. High-quality Skyrim fantasy RPG aesthetic."""

INSTRUCT_PROMPT_STYLE_CLAYMATION_DETAILED = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a claymation character. Make it look like a stop-motion clay animation render. Keep subject position and their pose the same as the reference. Ensure face follows claymation aesthetics with visible clay texture and hand-crafted appearance. Make sure anatomy shows tactile, sculpted clay surfaces. Make textures look like real clay with visible tool marks and fingerprints. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure warm studio lighting with soft shadows. Ensure clay seams and joint articulations are visible. Keep in focus. High-quality stop-motion claymation aesthetic."""

INSTRUCT_PROMPT_STYLE_CLAYMATION_SIMPLIFIED = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a simplified claymation character. Make it look like low-detail stop-motion clay animation render. Keep subject position and their pose the same as the reference. Ensure face has smooth, rounded clay forms with minimal surface detail. Make sure anatomy is simplified into basic geometric clay shapes. Make textures look smooth and featureless like basic sculpted clay. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure soft, even lighting with minimal shadows. Ensure simple joint articulations are clearly visible. Keep in focus. Simplified stop-motion claymation aesthetic."""

INSTRUCT_PROMPT_STYLE_SIMS = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a Sims 4 character. Make it look like a life simulation game render. Keep subject position and their pose the same as the reference. Ensure face follows Sims aesthetics with smooth poreless skin and expressive cartoon proportions. Make sure anatomy is stylized with soft, rounded forms. Make skin look smooth and slightly plasticky with subtle shading. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure bright global illumination lighting. Ensure vibrant, saturated colors throughout. Keep in focus. High-quality Sims game render."""

INSTRUCT_PROMPT_STYLE_STEAMPUNK = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify subject's appearance to look like a steampunk character. Make it look like a Victorian industrial aesthetic render. Keep subject position and their pose the same as the reference. Ensure face follows steampunk aesthetics with brass accents and goggles integration. Make sure anatomy features mechanical elements and gear details. Make textures look like weathered brass, copper, and industrial metal. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure warm, industrial lighting with sepia tones. Ensure mechanical details and gears are prominently featured. Keep in focus. High-quality steampunk aesthetic."""

INSTRUCT_PROMPT_STYLE_HORROR_MOVIE = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify the scene to match the cinematic horror movie style, featuring desaturated colors, dramatic shadows, and ominous atmosphere. Make it look like a scene from a psychological or supernatural horror film. Keep subject position and their pose the same as the reference. Ensure the environment conveys dread and unease following horror cinema aesthetics. Make sure lighting creates stark contrasts with deep shadows and unsettling highlights. Make textures look grimy, decayed, and foreboding. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure dim, shadowy lighting fits the horror mood. Ensure an atmosphere of suspense and supernatural dread is conveyed. Keep in focus. The result should be in a cinematic horror movie style."""

INSTRUCT_PROMPT_STYLE_PS1 = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify any subjects' appearance to match the low-polygon 3D style of PlayStation 1 games, featuring blocky geometry and pixelated textures. Make it look like a scene from a PS1-era video game. Keep subject position and their pose the same as the reference. Ensure the environment displays early 3D graphics with visible polygon edges and flat-shaded surfaces. Make sure anatomy is simplified with chunky, angular forms characteristic of PS1 character models. Make textures look pixelated and limited in color palette. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure flat, angular lighting fits the low-polygon aesthetic. Ensure prominent polygon edges and low-resolution textures are displayed. Keep in focus. The result should be in the classic PS1 3D video game style."""

INSTRUCT_PROMPT_STYLE_70S_SCIFI = """Keep pose. Keep angle. Keep eyes. Keep viewing direction. Modify the scene to match the retro-futuristic style of 1970s science fiction cinema, featuring film grain, practical effects aesthetic, and vintage color grading. Make it look like a scene from a 1970s sci-fi film. Keep subject position and their pose the same as the reference. Ensure the environment displays practical set design and early optical effects characteristic of 70s sci-fi movies. Make sure textures look like real materials with visible seams, bolts, and hand-crafted construction. Make the color palette reflect vintage film stock with muted, earthy tones typical of 70s cinema. Keep subject position and their pose the same as the reference. Make sure the subject is in the same position. Keep pose. Ensure soft, diffused lighting fits the vintage film aesthetic. Ensure visible film grain and practical lighting setups are displayed. Keep in focus. The result should be in the classic 1970s science fiction movie style."""
